#+title: Problem Set 5
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-17>
#+lastmod: <2025-10-19 20:46>
#+options: num:t
#+startup: overview

* Problem 1
** Task
Find gcd(11...1, 11...1)
            n       m

** Solution
*** With substitution
Let n = 3, m = 4

Therefore, gcd(111, 1111) =

1111 = 111 * 10 + 1
111 = 1 * 111 + 0

11111 = 111 * 100 + 11
111 = 11 * 10 + 1

111111 = 111 * 1000 + 111
111 = 111 * 1 + 0

111111 = 11 * 10000 + 1111
11 = 1111 * 1 - 1100
1111 = -1100 *

*** With n

* Problem 2 [DONE]
** Task
Find all n ∈ N for which the fraction (n^2 - n + 1)/(n^2 + 1) is irreduciable.

** Notes
- What exactly does this mean a fraction being irreducible?
  When the fraction can not be simplified any further.
- How am I supposed to find answer of all n values?
  Answer is basically a number set.
- Maybe I can check how it works for even and odd values of n?
  Not working
- No, I should try to use gcd((n^2 - n + 1), (n^2 + 1)) = 1

** Solution
*** Original
Let a = (n^2 - n + 1)
and b = (n^2 + 1)

Since a/b is irreducible, that implies gcd(a, b) = 1.

gcd((n^2 - n + 1), (n^2 + 1)) = 1

(n^2 - n + 1) = (n^2 + 1) * 1 - n
              = n^2 - n + 1
(n^2 + 1) = (-n)^2 + 1
-n = 1 * (-n) + 0

Thus, gcd((n^2 - n + 1), (n^2 + 1)) = 1. Meaning, (n^2 - n + 1)/(n^2 + 1) is irreduciable for all n ∈ N.

*** Polished
*Claim.* For n ∈ N, (n^2 - n + 1)/(n^2 + 1) is irreduciable.

*Proof.* Let d = gcd((n^2 - n + 1), (n^2 + 1)).
         Then, d | (n^2 - n + 1)-(n^2 + 1) = n.
         Hence, d|n and d|n^2. But, d|(n^2 + 1). Therefore, d divides
         (n^2 + 1) - n^2 = 1.

Thus d|1, so d = 1. Therefore, gcd((n^2 - n + 1), (n^2 + 1)) = 1, and the fraction is irreducible.

* Problem 3 [DONE]
** Task
Prove that if n is an odd integer, then n^2 ≡ 1 (mod 8).

** Solution
*CLaim.* If n is odd, n ∈ N, then n^2 ≡ 1 (mod 8).

*Proof.* Let n = 2k + 1, for k ∈ N, k >= 0.
         Then, (2k + 1)^2 = 4k^2 + 4k + 1
         4k^2 + 4k + 1 = 4(k^2 + k) + 1

         But 2|(k^2 + k), as
         (k^2 + k) = k(k + 1) (a product of 2 consequitive integers)
         k(k + 1) = 2m, m ∈ Z.

         Therefore,
         n^2 = 4 * 2m + 1
         n^2 = 8m + 1 ≡ 1 (mod 8).

         Thus every odd n satisfies n^2 ≡ 1 (mod 8).

* Problem 4 [DONE]
** Task
Find the remainder from the division of 2^2025 by 11.

** Solution
*** Revision of congruence
**** General
a ≡ b (mod n)

- This means that both a and b have same remainder if divided by n.
- a = kn + b
- n|(a - b)

**** Congruences properties
1. Compatability with addition/substraction:
   If a ≡ b (mod m) and c ≡ d (mod m), then
        a + c ≡ b + d (mod m)
        a - c ≡ b - d (mod m)

2. Compatability with multiplication:
   If a ≡ b (mod m) and c ≡ d (mod m), then
        a * c ≡ b * d (mod m)

3. Exponentiation rule:
   If a ≡ b (mod m), then for every integer r >= 1,
        a^r ≡ b^r (mod m)

4. Splitting exponents:
   For integers u, v, r,
        a^(uv+r) = (a^u)^v * a^r

*** Original
2^2025 = (2^10)^202 * 2^5

FML:
Since 11 is prime, then,
2^10 ≡ 1 (mod 11)

(2^10) ≡ 1 (mod 11)                     (raise to the power of 202 - exponentiation rule)
(2^10)^202 ≡ 1^202 (mod 11)             (multiply by integer 2^5 - multiplication rule)
(2^10)^202 * 2^5 ≡ 1^202 * 2^5 (mod 11) (simplify)
2^2025 ≡ 2^5 (mod 11)                   (simplify)
2^2025 ≡ 32 (mod 11)
2^2025 ≡ 10 (mod 11)

* Problem 5
** Task
Solve the equation x^2 - 16y = 3, where x, y ∈ Z.

** Solution

* Problem 6
** Task

** Solution

* Problem 7
** Task
Find all p ∈ N such that p, p + 10, and p + 14 are prime numbers.

** Solution

* Problem 8 [DONE]
** Task
It is October today. What are the chances that, in 250 months’ time, people will be swimming in the Danube?

** Solution
250 + 10 = 260 (starting from January)
260 % 12 = 8
8 month is August
Thus, highly likely.

* Problem 9 [DONE]
** Task
Prove that there exists an n ∈ N for which 11 | (2^n − 1).

** Solution
#+begin_src julia :results output
function get_n()
    n = 1

    while true
        if (2^n - 1) % 11 == 0
            println(n)
            break
        end
        n += 1
    end
end

get_n()

#+end_src

#+RESULTS:
: get_n (generic function with 1 method)
: 10

* Problem 10 [DONE]
** Task
Prove that there exists a power of 3 that ends with the digits 001. (In other words, 3n = ...001 for some n ∈ N.)

** Solution
#+begin_src julia :results output
function is_wanted(num::BigInt)
    if num > 1000 && num % 1000 == 1
        return true
    end
    return false
end

function get_num()
    i = 1
    while true
        n = BigInt(3)^i
        if is_wanted(n)
            println("Number is: 3^$i = ", n)
            break
        end
        i += 1
    end
end

get_num()
#+end_src

#+RESULTS:
: is_wanted (generic function with 1 method)
: get_num (generic function with 1 method)
: Number is: 3^100 = 515377520732011331036461129765621272702107522001

* Problem 11 [DONE]
** Task
A natural number is called perfect if it is equal to the sum of all its divisors. For example, 28 is perfect, because 28 = 1 + 2 + 4 + 7 + 14. Find all perfect numbers under 10000.

** Solution
#+begin_src julia :results output
function is_perfect_natural(num::Int)
    arr = Int[]

    for i in 1:1:num / 2
        if num % i == 0
            push!(arr, i)
        end
    end
    return num == sum(arr)
end

function get_perfect_naturals()
    limit = 10000
    arr = Int[]

    for i in 1:1:limit
        if (is_perfect_natural(i))
            push!(arr, i)
        end
    end
    return arr
end

println(get_perfect_naturals())
#+end_src

#+RESULTS:
: is_perfect_natural (generic function with 1 method)
: get_perfect_naturals (generic function with 1 method)
: [6, 28, 496, 8128]
