#+title: Problem Set 7
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-24>
#+lastmod: <2025-10-25 18:48>
#+options: num:t
#+startup: overview

* Problem 1
** Task
Define R on Z a mRn <--> 2|(m^2 + n^2) for all m,n ∈ Z. Is R an equivalence relation?

** Solution
A relation R is an equivalence relation if it is reflexive, symmetric and transitive.

* Problem 2 [DONE]
*Problem topic:* Relations - Equivalence.

** Task
Let R be a relation on the real numbers defined by xRy <--> x^2 = y^2. Is R an equivalence relation.

** Solution
*** Notes
The equivalence relation should follow the following points:

#+begin_quote
- a~a for all a ∈ Z.
- If a~b, then b~a for all and a,b ∈ Z.
- If a~b and b~c, then a~c for all a,b,c ∈ Z.
#+end_quote

Example:
|-----------+---+---+---|
| x^2 = y^2 | 1 | 2 | 3 |
|-----------+---+---+---|
|         1 | T | F | F |
|-----------+---+---+---|
|         2 | F | T | F |
|-----------+---+---+---|
|         3 | F | F | T |
|-----------+---+---+---|

The table does not violate any of the mentioned constraints, as it:
- has a~a for all a ∈ Z.
- does not have a~b, therefore no b~a for all and a,b ∈ Z.
- does not have a~b and b~c, therefore no a~c for all a,b,c ∈ Z.

Therefore, R is an equivalence relation.

**** My wording
- Relation must be reflexive
  Meaning that there should be all a,b ∈ A. (i.e. {(1,1), (2, 2), (3, 3), ...})

- Relation must be symmetric
  Meaning that if there is a (a,b) there should also be (b,a)

- Relation must be transitive
  Meaning that if aRb and bRc, there should be aRc

**** Formal notation
#+begin_quote
- a~a for all a ∈ Z.
- If a~b, then b~a for all and a,b ∈ Z.
- If a~b and b~c, then a~c for all a,b,c ∈ Z.
#+end_quote

**** Formal equivalence recreation
#+begin_quote
- a~a for all a ∈ Z.
- If a~b, then b~a for all a,b ∈ Z.
- If a~b and b~c, then a~c for all a,b,c ∈ Z.
#+end_quote

*** Solution
**** Original
#+begin_quote
*Formal Definition*
An *equivalence relation* on a set A is an ordered relationship between pairs of elements of A for which the pair is either related of is not relatied. If a,b ∈ A, we denote a~b if a is related to b, and a!~b if a is not related to b.

Additionally, for ~ to be an equivalence relation, it also must satisfy the following three properties:
- *Reflexive:* a~a for all a ∈ A.
- *Symmetric:* if a~b, then b~a for all a,b ∈ A.
- *Transitive:* if a~b and b~c, then a~c for all a,b,c ∈ A.
#+end_quote

Since xRy <--> x^2 = y^2,
        xRy <--> x^2 = y^2      (take root from both sides)
        xRy <--> x = y.

xRy <--> x = y is a~a for all a ∈ Z.

Now I feel a little bit stuck as I intuitively know that it is also true for 2 other points, but not sure how to formulate it.
**** Polished
#+begin_quote
*Formal Definition*
An *equivalence relation* on a set A is an ordered relationship between pairs of elements of A for which the pair is either related of is not relatied. If a,b ∈ A, we denote a~b if a is related to b, and a!~b if a is not related to b.

Additionally, for ~ to be an equivalence relation, it also must satisfy the following three properties:
- *Reflexive:* a~a for all a ∈ A.
- *Symmetric:* if a~b, then b~a for all a,b ∈ A.
- *Transitive:* if a~b and b~c, then a~c for all a,b,c ∈ A.
#+end_quote

*Proof.*
- *Reflexive:* For any x ∈ R, x^2 = x^2. Hence xRx.
- *Symmetric:* If xRy, then x^2 = y^2. That equality is symmetric, so x^2 = y^2, hence xRy.
- *Transitive:* If xRy and yRz, then x^2 = y^2 and y^2 = z^2. Thus, x^2 = z^2, so xRz.

Since all three hold, R is an equivalence relation.

* Problem 3
*Problem topic:* Relations - Equivalence.
** Task
Define R on Z as xRy <--> 4|(x + 3y) for all x,y ∈ Z. Is R an equivalence relation?

** Solution
*** Notes
#+begin_quote
- a~a for all a ∈ A.
- If a~b, then b~a for all a,b ∈ A.
- If a~b and b~c, then a~c for all a,b,c ∈ A.
#+end_quote

- Other ways to write it
  4|(x + 3y)
  4k = x + 3y for k ∈ Z.
  x + 3y ≡ 0 (mod 4)

Truth table:
|----------------+---+---+---|
| x+3y≡0 (mod 4) | 1 | 2 | 3 |
|----------------+---+---+---|
|              1 | T | F | F |
|----------------+---+---+---|
|              2 | F | T | F |
|----------------+---+---+---|
|              3 | F | F | T |
|----------------+---+---+---|

This table leads to my hypothesis of truth table being only true for the x=y.
Maybe I should prove that there are no other combination except of x=y that would satisfy the relation?

*HINT:*

3 ≡ -1 (mod 4)
3 ≡ -1 + 4 (mod 4)
3y ≡ -y + 4y (mod 4)
So 3y and -y differ by the multiple of 4
3y ≡ -y (mod 4)
Thus,
x - y ≡ 0 (mod 4)
Therefore,
x + 3y ≡ x - y (mod 4)
Therefore,
4|(x + 3y) iff x - y ≡ 0 (mod 4)
i.e. x ≡ y (mod 4)

proof tryout:
#+begin_quote
*Proof.*
- *Reflexive:* For any x ∈ Z, x + 3x = 4x; so 4|(x+3x). Thus xRx.
- *Symmetric:* If xRy, then x + 3y ≡ 0 (mod 4). Since 3 ≡ -1 (mod 4), this gives x - y ≡ 0 (mod 4). Hence y - x ≡ 0 and y + 3x ≡ 0 (mod 4). So yRx.
- *Transitive:*
#+end_quote

*** Solution

* Problem 4
** Task
** Solution
* Problem 5
** Task
** Solution
* Problem 6
** Task
** Solution
* Problem 7
** Task
** Solution
* Problem 8
** Task
A relation R on ℝ is defined as xRy, <--> |x| <= |y|. Is this a total order?

** Solution
* Problem 9
** Task
** Solution
* Problem 10
** Task
** Solution
* Problem 11
** Task
** Solution
* Problem 12
** Task
** Solution
* Problem 13
** Task
** Solution
* ERROR LOGS
