#+title: Problem Set 7
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-24>
#+lastmod: <2025-10-27 12:42>
#+options: num:t
#+startup: overview

* How to prove equivalence relation?
Proof sceleton.

1. *State goal briefly.*
   /Goal:/ show ~ is reflexive, symmetric, transitive on A.

2. *Relfexive.*
   Let a ∈ A. Show a~a. (one sentence: reason why the relation includes (a,a) or why the property holds.)

   Therefore, ∀a ∈ A, a~a.

3. *Symmetric.*
   Let a,b ∈ A, and assume a~b. Show b~a. (once sentence: use definition or algebraic symmetry.)

   Therefore, ∀a,b ∈ A, a~b --> b~a.

4. *Transitive.*
   Let a,b,c ∈ A, and assume a~b and b~c. Show a~c. (one sentence: combine assumptions via definition/transitivity property.)

   Therefore, ∀a,b,c ∈ A, (a~b ∧ b~c) --> a~c.

5. *Conclude.*
   Since three properties hold, ~ is an equivalence relation.

* Problem 1 [SKIP]
** Task
Define R on Z a mRn <--> 2|(m^2 + n^2) for all m,n ∈ Z. Is R an equivalence relation?

** Solution
A relation R is an equivalence relation if it is reflexive, symmetric and transitive.

* Problem 2 [DONE]
*Problem topic:* Relations - Equivalence.

** Task
Let R be a relation on the real numbers defined by xRy <--> x^2 = y^2. Is R an equivalence relation?

** Solution
*** Notes
The equivalence relation should follow the following points:

#+begin_quote
- a~a for all a ∈ Z.
- If a~b, then b~a for all and a,b ∈ Z.
- If a~b and b~c, then a~c for all a,b,c ∈ Z.
#+end_quote

Example:
|-----------+---+---+---|
| x^2 = y^2 | 1 | 2 | 3 |
|-----------+---+---+---|
|         1 | T | F | F |
|-----------+---+---+---|
|         2 | F | T | F |
|-----------+---+---+---|
|         3 | F | F | T |
|-----------+---+---+---|

The table does not violate any of the mentioned constraints, as it:
- has a~a for all a ∈ Z.
- does not have a~b, therefore no b~a for all and a,b ∈ Z.
- does not have a~b and b~c, therefore no a~c for all a,b,c ∈ Z.

Therefore, R is an equivalence relation.

**** My wording
- Relation must be reflexive
  Meaning that there should be all a,b ∈ A. (i.e. {(1,1), (2, 2), (3, 3), ...})

- Relation must be symmetric
  Meaning that if there is a (a,b) there should also be (b,a)

- Relation must be transitive
  Meaning that if aRb and bRc, there should be aRc

**** Formal notation
#+begin_quote
- a~a for all a ∈ Z.
- If a~b, then b~a for all and a,b ∈ Z.
- If a~b and b~c, then a~c for all a,b,c ∈ Z.
#+end_quote

**** Formal equivalence recreation
#+begin_quote
- a~a for all a ∈ Z.
- If a~b, then b~a for all a,b ∈ Z.
- If a~b and b~c, then a~c for all a,b,c ∈ Z.
#+end_quote

*** Solution
**** Original
#+begin_quote
*Formal Definition*
An *equivalence relation* on a set A is an ordered relationship between pairs of elements of A for which the pair is either related of is not relatied. If a,b ∈ A, we denote a~b if a is related to b, and a!~b if a is not related to b.

Additionally, for ~ to be an equivalence relation, it also must satisfy the following three properties:
- *Reflexive:* a~a for all a ∈ A.
- *Symmetric:* if a~b, then b~a for all a,b ∈ A.
- *Transitive:* if a~b and b~c, then a~c for all a,b,c ∈ A.
#+end_quote

Since xRy <--> x^2 = y^2,
        xRy <--> x^2 = y^2      (take root from both sides)
        xRy <--> x = y.

xRy <--> x = y is a~a for all a ∈ Z.

Now I feel a little bit stuck as I intuitively know that it is also true for 2 other points, but not sure how to formulate it.
**** Polished
#+begin_quote
*Formal Definition*
An *equivalence relation* on a set A is an ordered relationship between pairs of elements of A for which the pair is either related of is not relatied. If a,b ∈ A, we denote a~b if a is related to b, and a!~b if a is not related to b.

Additionally, for ~ to be an equivalence relation, it also must satisfy the following three properties:
- *Reflexive:* a~a for all a ∈ A.
- *Symmetric:* if a~b, then b~a for all a,b ∈ A.
- *Transitive:* if a~b and b~c, then a~c for all a,b,c ∈ A.
#+end_quote

*Proof.*
- *Reflexive:* For any x ∈ R, x^2 = x^2. Hence xRx.
- *Symmetric:* If xRy, then x^2 = y^2. That equality is symmetric, so x^2 = y^2, hence xRy.
- *Transitive:* If xRy and yRz, then x^2 = y^2 and y^2 = z^2. Thus, x^2 = z^2, so xRz.

Since all three hold, R is an equivalence relation.

* Problem 3 [DONE]
*Problem topic:* Relations - Equivalence.
** Task
Define R on Z as xRy <--> 4|(x + 3y) for all x,y ∈ Z. Is R an equivalence relation?

** Solution
*** Notes
#+begin_quote
- a~a for all a ∈ A.
- If a~b, then b~a for all a,b ∈ A.
- If a~b and b~c, then a~c for all a,b,c ∈ A.
#+end_quote

- Other ways to write it
  4|(x + 3y)
  4k = x + 3y for k ∈ Z.
  x + 3y ≡ 0 (mod 4)

Truth table:
|----------------+---+---+---|
| x+3y≡0 (mod 4) | 1 | 2 | 3 |
|----------------+---+---+---|
|              1 | T | F | F |
|----------------+---+---+---|
|              2 | F | T | F |
|----------------+---+---+---|
|              3 | F | F | T |
|----------------+---+---+---|

This table leads to my hypothesis of truth table being only true for the x=y.
Maybe I should prove that there are no other combination except of x=y that would satisfy the relation?

*HINT:*

3 ≡ -1 (mod 4)
3 ≡ -1 + 4 (mod 4)
3y ≡ -y + 4y (mod 4)
So 3y and -y differ by the multiple of 4
3y ≡ -y (mod 4)
Thus,
x - y ≡ 0 (mod 4)
Therefore,
x + 3y ≡ x - y (mod 4)
Therefore,
4|(x + 3y) iff x - y ≡ 0 (mod 4)
i.e. x ≡ y (mod 4)

proof tryout:
#+begin_quote
*Proof.*
- *Reflexive:* For any x ∈ Z, x + 3x = 4x; so 4|(x+3x). Thus xRx.
- *Symmetric:* If xRy, then x + 3y ≡ 0 (mod 4). Since 3 ≡ -1 (mod 4), this gives x - y ≡ 0 (mod 4). Hence y - x ≡ 0 and y + 3x ≡ 0 (mod 4). So yRx.
- *Transitive:*
#+end_quote

*** Solution
**** Original
1. *Goal.* Show ~ <--> 4|(x + 3y) is an equivalence relation for all x,y ∈ Z.

2. *Reflexive.*
   Let x ∈ Z. Therefore, (x + 3x) = 4x. Thus, 4|4x for all x ∈ Z.

   Therefore, ∀x ∈ Z, x~x.

3. *Symmetric.* (show b~a; 4|(y + 3x))
   Let x,y ∈ Z. Assume 4|(x + 3y). Therefore,

   x + 3y ≡ 0 (mod 4)

   Notice:
   3 ≡ -1 (mod 4)
   3y ≡ -1y (mod 4)

   Thus,
   x + 3y - 3y ≡ 0 + y (mod 4)
   x ≡ y (mod 4)
   x - y ≡ 0 (mod 4)
   2x - 2y ≡ 0 (mod 4)

   Hence,
   x + 3y ≡ 0 (mod 4)
   x + 3y + 2x - 2y ≡ 0 (mod 4)
   3x + y ≡ 0 (mod 4)

   Therefore, ∀x,y ∈ Z, x~y --> y~x.

4. *Transitive.*
   Let x,y,z ∈ Z. Assume 4|(x + 3y) and 4|(y + 3z). Therefore,

   Going through all steps from /Symmetric/, we come to:

   x ≡ y (mod 4);
   y ≡ z (mod 4).

   Thus,
   x ≡ z (mod 4)

   And since x ≡ z (mod 4), we can go backwards in steps of /Symmetric/, and get:

   x + 3z ≡ 0 (mod 4)

   Therefore, ∀x,y,z ∈ Z, (x~y ∧ y~x) --> x~z.

5. *Conclusion.*
   Since three properties holds, ~ is an equivalence relation.

**** Polished
Let R on Z be defined as xRy <--> 4|(x + 3y).

*Goal.* Show R is an equivalence relation.

*Relfexive.* Let x ∈ Z. Then, x + 3x = 4x, and 4|4x.

Therefore, ∀x ∈ Z, x~x.

*Symmetric.* Let x,y ∈ Z. Assume xRy, i.e. 4|(x + 3y).

Since,
3 ≡ -1 (mod 4)
3y ≡ -y (mod 4)

Thus,
x + 3y ≡ x - y ≡ 0 (mod 4)
x ≡ y (mod 4)

Hence,
y + 3x ≡ 0 (mod 4)

Therefore, ∀x,y ∈ Z, x~y --> y~x.

*Transitive.* Let x,y,z ∈ Z. Assume xRy and yRz.

From the same simplification, we get x ≡ y (mod 4) and y ≡ z (mod 4).

Hence, x ≡ z (mod 4). Thus,

x + 3z ≡ z + 3z ≡ 4z ≡ 0 (mod 4)

Therefore, ∀x,y,z ∈ Z, (x~y ∧ y~x) --> x~z.

*Conclusion.*
R is relfexive, symmetric and transitive, so it is an equivalence relation.

* Problem 4 [DONE]
** Task
Prove or disprove: If R is an equivalence relation on an infinite set S, then R has infinitely many equivalence classes.

** Solution
*** Notes
- What is an equivalence class?
  An equivalence class is a subset of a set where all elements are related to each other by an equivalence relation, which must be reflexive, symmetric, and transitive.

Yes, intuitively I would agree that there are infinitely many equivalence classes on equivalence relation R on an infinite set.

However, looking on the example of equivalence relation xRy <--> x^2 = y^2, for x,y ∈ Z, we can notice that (x)^2 = (-y)^2, which leads to assumption that there might be greater infinite classes than infinite set.
- My assumtion was wrong, since the example like (x)^2 = (-y)^2 fall within one class, and not to separate different ones.

However, looking on the example of x mod y = 0 ...
- x mod y = 0 is not an equivalence relation.

*** Solution
*Goal.* Find an equivalence relation that would result in finite equivalence classes.

- *Proof.* xRy <--> 2|(x + y)

  *Goal.* xRy <--> 2|(x + y) is an equivalence relation for x,y ∈ Z.

  *Reflexive.* Let x ∈ Z. Then, x + x = 2x, and 2|2x.

  Therefore, ∀x ∈ Z, x~x.

  *Symmetric.* Let x,y ∈ Z. Assume xRy, i.e. x + y ≡ 0 (mod 2). Then,

  x + y = y + x ≡ 0 (mod 2).

  Therefore, ∀x,y ∈ Z, x~y --> y~x.

  *Transitive.* Let x,y,z ∈ Z. Assume xRy and yRz. Then,

  (x + y) + (y + z) ≡ 0 (mod 2)

  x + 2y + z ≡ 0 (mod 2)

  Thus,

  x + z ≡ 0 (mod 2)

  Therefore, ∀x,y,z ∈ Z, (x~y ∧ y~x) --> x~z.

  *Conclusion.*
  R is reflexive, symmetric and transitive, so it is an equivalence relation.

Therefore, xRy <--> 2|(x + y) equivalence relation, produce 2 infinite classes:

- the even integers: [0] = {..., -4, -2, 0, 2, 4, ...}
- the odd integers: [1] = {..., -3, -1, 1, 3, 5 ...}

Therefore the statement is false, since equivalence relation on infinite set, may have finite equivalence classes.

* Problem 5 [DONE]
** Task
There are five different equivalence relations on the set A = {a,b,c}. Describe them all. (Here you can just draw a picture instead of text if you prefer.)

** Solution
|---+---+---+---|
|   | a | b | c |
|---+---+---+---|
| a | T |   |   |
|---+---+---+---|
| b |   | T |   |
|---+---+---+---|
| c |   |   | T |
|---+---+---+---|

|---+---+---+---|
|   | a | b | c |
|---+---+---+---|
| a | T | T |   |
|---+---+---+---|
| b | T | T |   |
|---+---+---+---|
| c |   |   | T |
|---+---+---+---|

|---+---+---+---|
|   | a | b | c |
|---+---+---+---|
| a | T |   |   |
|---+---+---+---|
| b |   | T | T |
|---+---+---+---|
| c |   | T | T |
|---+---+---+---|

|---+---+---+---|
|   | a | b | c |
|---+---+---+---|
| a | T |   | T |
|---+---+---+---|
| b |   | T |   |
|---+---+---+---|
| c | T |   | T |
|---+---+---+---|

|---+---+---+---|
|   | a | b | c |
|---+---+---+---|
| a | T | T | T |
|---+---+---+---|
| b | T | T | T |
|---+---+---+---|
| c | T | T | T |
|---+---+---+---|

* Problem 6 [DONE]
** Task
Let S be the set of all triangles in the plane. Define T1 ~ T2 if T1 is similar to T2. Prove that ~ is an equivalence relation.

** Solution
*** Notes
- What does the "similar triangle" mean?
  It means the triangles with equal angles and prortional sides.

  Thus, two triangles are related if one can be obtained from the other by resizing (scaling), possibly rotating or flipping.

*** Solution
*Remark.* Two triangles are similar iff their corresponding angles are equal (equivalently, corresponding lengths are proportional).

*Proof.*

*Reflexive.* For any triangle T ∈ S the identity map is a similarity taking T to itself. Thus, T~T for all T ∈ S.

*Symmetric.* If T1~T2, then there exists a similarity transformation f that makes T2 of T1. Similarity transformations are invertible and their inverses are again similarity transformations. The inverse f^-1 turns T2 to T1, so T2~T1.

*Transitive.* If T1~T2 and T2~T3, let f be similarity mapping T1 to T2 and g a similarity mapping T2 to T3. The composition f*g is again a similarity transformation, and maps T1 to T3. Hence T1~T3.

*Conclusion.* Since ~ is reflexive, symmetric and transitive, it is an equivalence relation on S.

* Problem 7 [DONE]
** Task
Consider the partition P = {{0}, {-1,1}, {-2,2}, {-3,3}, ...} of Z. Describe the equivalence relation whose equivalence classes are the elements of P.

** Solution
Its xRy <--> x^2 = y^2 for x,y ∈ Z.

(solved quickly because of the Problem 4)

* Problem 8 [SKIP]
** Task
A relation R on ℝ is defined as xRy, <--> |x| <= |y|. Is this a total order?

** Solution
* Problem 9 [IN PROGRESS]
** Task
In a basketball tournament, each team plays every other team exactly once. Define a relation ≼ on the set of all teams as: for two teams A and B, we say A ≼ B <--> the final ranking of B is at least as high as that of A. Is ≼ a partial order? Is it a total order?

** Notes
- What is the difference between the =partial order= and the =total order=?
  A partial order satisfies three conditions:

  - *Reflexivity:* Every element is less than or equal to itself. a ≼ a.

  - *Antisymmetry:* If a ≼ b and b ≼ a then a = b.

  - *Transitivity:* If a ≼ b and b ≼ c then a ≼ c.

  It is a "partial" because not every pair of elements need to be comparable. For example, in a set of subsets, set A is only less than or equal to set B if every member of A is also a member of B.

  A total order is a partial order with the additional property of compatability or totality.

  - *Compatability/Totality:* For any two elements a and b, a ≼ b or b ≼ a.

  In a total order, every pair of  elements is comparable. For example, the usual order of numebrs is a total order because of any two numbers, one number is always less than or equal to the other.


** Solution

* Problem 10 [IN PROGRESS]
** Task
A relation ≼ on R^2 is defined as
        (x1, y1) ≼ (x2, y2) <--> |x2 - x1| <= y2 - y1.

Prove that ≼ is a partial order. Is it a total order?

** Solution
* Problem 11
** Task
** Solution
* Problem 12
** Task
** Solution
* Problem 13
** Task
** Solution
* ERROR LOGS
