#+title: Day 08: Synthesis & Pre-Mock Drilling
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-02-21>
#+lastmod: <2026-04-13 17:28>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages

* Block A: Active Computation
** Task
#+begin_quote
1. (7 points) Determine, for the map

   \begin{align*}
   f: \mathbb{Z}_{5}^{3} \rightarrow \mathbb{Z}_{5}^{3}, \quad
   x \mapsto
   \left(\begin{array}{c}
   3x_{1} + 4x_{2} + 2x_{3} \\
   x_{1}  + 3x_{2} + x_{3}  \\
   4x_{1} + 2x_{2} + 2x_{3} \\
   \end{array}\right)
   \end{align*}

   the set of all points $x \in \mathbb{Z}_{5}^{3}$ with

   \begin{align*}
   f(x)=
   \left(\begin{array}{l}
   1 \\
   3 \\
   1 \\
   \end{array}\right)
   \end{align*}
#+end_quote

** Solution

\begin{align*}
\left[ \begin{array}{ccc|c}
3 & 4 & 2 & 1 \\
1 & 3 & 1 & 3 \\
4 & 2 & 2 & 1 \\
\end{array} \right]
\end{align*}

\begin{align*}
1 - (m_{21})(3) &\equiv 0 \quad (mod \, 5) \\
m_{21} &= 2 \\
(2, 2) &= 3 - (2)(4) = -5 \equiv 0 \\
(2, 3) &= 1 - (2)(2) = -3 \equiv 2 \\
(2, 4) &= 3 - (2)(1) = 1 \\
\end{align*}

\begin{align*}
\implies
\left[ \begin{array}{ccc|c}
3 & 4 & 2 & 1 \\
0 & 0 & 2 & 1 \\
4 & 2 & 2 & 1 \\
\end{array} \right]
\end{align*}

\begin{align*}
4 - (m_{31})(3) &\equiv 0 \quad (mod \, 5) \\
m_{31} &= 3 \\
(3, 2) &= 2 - (3)(4) = -10 \equiv 0 \\
(3, 3) &= 2 - (3)(2) = -4 \equiv 1 \\
(3, 4) &= 1 - (3)(1) = -2 \equiv 3 \\
\end{align*}

\begin{align*}
\implies
\left[ \begin{array}{ccc|c}
3 & 4 & 2 & 1 \\
0 & 0 & 2 & 1 \\
0 & 0 & 1 & 3 \\
\end{array} \right]
\end{align*}

Note that the second and third rows are dependent, as $R_3 \times 2 = R_2$.

\begin{align*}
\implies
\left[ \begin{array}{ccc|c}
3 & 4 & 2 & 1 \\
0 & 0 & 2 & 1 \\
0 & 0 & 0 & 0 \\
\end{array} \right]
\end{align*}

Hence,

\begin{align*}
(2)x_3 &\equiv 1 \quad (mod \, 5) &\implies x_3 &= 3 \\
(0)x_2 + (0)x_3 &\equiv 0 \quad (mod \, 5) &\implies x_2 &= n, \forall n \in \mathbb{Z}_5 \\
(3)x_1 + (4)x_2 + (2)x_3 &\equiv 1 \quad (mod \, 5) &\implies x_1 &= 2n \\
\end{align*}

Thus, the solution set is:

$$\left\{ \left( 2n, n, 3 \right) \mid \forall n \in \mathbb{Z}_{5} \right\}$$

** Review Metrics
- Time Spent: hour, was confused with $\mathbb{Z}_5$.
- Confidence (1-5): 5
- Mistakes / Takeaways: none

* Block B: Theory & Proof Memorization
** Task

** Solution

** Review Metrics
- Time Spent:
- Confidence (1-5):
- Mistakes / Takeaways:

* Block C: Application/Testing
** Task
#+begin_quote
a) (2 points) Define the notions sum, direct sum, and complement for subspaces of a vector space.
b) (2 points) State the dimension theorem for sums of subspaces of a $K$ -vector space.
c) (6 points) Prove the dimension theorem for sums of subspaces of a $K$ -vector space. You do not have to prove additional results used in your proof, but you must clearly indicate which theorems/propositions you use (by stating them precisely).
#+end_quote

** Solution
*** (a)

- $V + W := \left\{ v + w : v \in V, w \in W \right\}$

- $V \oplus W$ is a sum where $V \cap W = \left\{ 0 \right\}$

- $W$ is a complement of $V$ iff $V \oplus W = U$

*** (b) + (c)

Let $U_1, U_2$ be finite subspaces of vector space $V$. Define $I := U_1 \cap U_2$ and choose basis $B_I = \left\{ w_1, \cdots, w_k \right\}$. Extend $B_I$ to basis $U_1$ and $U_2$:

$$B_{U_1} = \left\{ w_1, \cdots, w_k, u_1, \cdots, u_p \right\} \quad B_{U_2} = \left\{ w_1, \cdots, w_k, v_1, \cdots, v_q \right\}$$

Claim: constructed $B = \left\{ w_1, \cdots, w_k, u_1, \cdots, u_p, v_1, \cdots v_q \right\}$ is basis of $U_1 + U_2$.

Span is immediate. Let $x \in U_1 + U_2$. It can be represented as $x = x_1 + x_2 : x_1 \in U_1, x_2 \in U_2$, hence it can be represented as scalar sum of their basis $B_{U_1}$ and $B_{U_2}$.

Linear independence. Assume $\sum \alpha_i w_i + \sum \beta_j u_j + \sum \gamma_l v_l = 0$. Rearange,

$$\sum \gamma_l v_l = - \left( \sum \alpha_i w_i + \sum \beta_j u_j  \right) \in U_1$$

As LHS is in $U_2$, the RHS must be in $U_1 \cap U_2$, and hence could be written as $\sum \mu_i w_i$. Thus,


$$\sum \gamma_l v_l - \sum \mu_i w_i = 0$$

Linear independence of $B_{U_2}$ forces all $\gamma_l = 0$. Substituting back:

$$\sum \alpha_i w_i + \sum \beta_j u_j = 0$$

Linear independence of $B_{U_1}$ forces $\alpha_i = \beta_j = 0$. Hence $B$ is linearly independent.

Therefore, as $B$ is basis of $U_1 + U_2$,

$$dim(U_1 + U_2) = k + p + q = (p + k) + (q + k) - k = |U_1| + |U_2| - |U_1 \cap U_2|$$

** Review Metrics
- Time Spent:
- Confidence (1-5):
- Mistakes / Takeaways:

