#+title: Day 03: Linear Maps & Systems Integration
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-02-21>
#+lastmod: <2026-04-13 17:28>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages

* Block A: Active Computation
** Task
#+begin_quote
19. (18) Linear systems of equations, Reduced row echelon form

(a) (12) Solve the following linear system of equations using Gaussian elimination, i.e., an LU-decomposition (possibly with partial pivoting)

$(2+i)  z_1 + (-1+3i) z_2 + (4-i)  z_3 + (1+2i) z_4 = 5+24i$,
$(3-2i) z_1 + (2+i)   z_2 + (-1+i) z_3 + 5      z_4  = 24 - 7i$,
$(-2+i) z_1 + (1-4i)  z_2 + (3+2i) z_3 + (-1+i) z_4 = -14 - 2i$,
$(1+3i) z_1 - 2       z_2 + (2-i)  z_3 + (4+i)  z_4 = 7 + 10i$.


(b) (6) Transform the following real $4\times5$ matrix into reduced row echelon form:

$$A=\begin{pmatrix}12&6&4&-7&-3\\ -6&-3&12&7&1\\ 6&3&-8&-6&4\\ 18&9&4&-11&2\end{pmatrix}$$
#+end_quote

** Solution
*** (a)

\begin{align*}
\left[ \begin{array}{cccc|c}
(2+i)  & (-1+3i) & (4-i)  & (1+2i) & (5+24i)    \\
(3-2i) & (2+i)   & (-1+i) & (5)    & (24 - 7i)  \\
(-2+i) & (1-4i)  & (3+2i) & (-1+i) & (-14 - 2i) \\
(1+3i) & (-2)    & (2-i)  & (4+i)  & (7 + 10i)  \\
\end{array} \right]
\end{align*}

\begin{align*}
|a_{11}| &= |2 + i| = \sqrt{5} \\
|a_{21}| &= |3 - 2i| = \sqrt{13} \\
|a_{31}| &= |-2 + i| = \sqrt{5} \\
|a_{41}| &= |1 + 3i| = \sqrt{10} \\
\end{align*}

\begin{align*}
P_1A &=
\begin{bmatrix}
0 & 1 & 0 & 0 \\
1 & 0 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
(2+i)  & (-1+3i) & (4-i)  & (1+2i) \\
(3-2i) & (2+i)   & (-1+i) & (5)    \\
(-2+i) & (1-4i)  & (3+2i) & (-1+i) \\
(1+3i) & (-2)    & (2-i)  & (4+i)  \\
\end{bmatrix} \\
&=
\begin{bmatrix}
(3-2i) & (2+i)   & (-1+i) & (5)    \\
(2+i)  & (-1+3i) & (4-i)  & (1+2i) \\
(-2+i) & (1-4i)  & (3+2i) & (-1+i) \\
(1+3i) & (-2)    & (2-i)  & (4+i)  \\
\end{bmatrix} \\
\end{align*}

$$l_{21} = \dfrac{2+i}{3-2i} = \dfrac{(2+i)(3+2i)}{13} = \dfrac{6 + 7i + 2i^{2}}{13} =  \dfrac{4 + 7i}{13}$$

\begin{align*}
P_1A =
&\begin{bmatrix}
(3-2i) & (2+i)   & (-1+i) & (5)    \\
(2+i)  & (-1+3i) & (4-i)  & (1+2i) \\
(-2+i) & (1-4i)  & (3+2i) & (-1+i) \\
(1+3i) & (-2)    & (2-i)  & (4+i)  \\
\end{bmatrix} \\
\xrightarrow{l_{21} = \dfrac{4+7i}{13}}
&\begin{bmatrix}
(3-2i) & (2+i)   & (-1+i) & (5)    \\
(2+i)  & (-1+3i) & (4-i)  & (1+2i) \\
(-2+i) & (1-4i)  & (3+2i) & (-1+i) \\
(1+3i) & (-2)    & (2-i)  & (4+i)  \\
\end{bmatrix} \\
\end{align*}

No, I don't want to solve this bullshit.

** Review Metrics
- Time Spent:
- Confidence (1-5):
- Mistakes / Takeaways:

* Block B: Theory & Proof Memorization
** Task
#+begin_quote
Learn and memorize Kernel and Image properties (Proposition III.2.11).
#+end_quote

** Solution

*** Annotated Rewriting

Let $V$ and $W$ be vector spaces over $\mathbb{F}$ and let $f : V \rightarrow W$ be linear. Then,

a. If $\hat{V} \subseteq V$ is a subspace, then $f(\hat{V}) \subseteq W$ is also a subspace. In particular $im(f) \subseteq W$ is a subspace.
b. If $\hat{W} \subseteq W$ is a subspace, then $f^{-1}(\hat{W}) \subseteq V$ is also a subspace. In particular, $ker(f) \subseteq V$ is a subspace.
c. $f$ is surjective if and only if $im(f) = W$.
d. $f$ is injective if and only if $ker(f) = \left\{ 0 \right\}$.

*Proofs.*

a. Let $w, w' \in f(\hat{V})$ and $\lambda \in \mathbb{F}$.

   /define $w$, $w'$ to be elements of $f(\hat{V})$ (or saying differently, image of subspace $\hat{V}$ under $f$) and $\lambda$ (which is element/scalar of a field) to be used for subspace criterion (where given any linear combination $\lambda w + w' \in f(\hat{V})$, given $w, w' \in f(\hat{V}), \, \lambda \in \mathbb{F}$)/

   Then there exist $v, v' \in \hat{V}$ with $f(v) = w$ and $f(v') = w'$.

   /letting $w, w' \in f(\hat{V})$ strictly implies existence of $v, v' \in \hat{V} : f(v) = w, f(v') = w'$/

   By linearity of $f$ we obtain $\lambda w + w' = \lambda f(v) + f(v') = f(\lambda v + v')$.

   /linearity of $f$ (linear map) implies $\lambda f(v) + f(v') = f(\lambda v + v')$ (remember $\lambda w + w' = \lambda f(v) + f(v')$)/

   Since $\hat{V}$ is a subspace, we have $\lambda v + v' \in \hat{V}$, and hence $\lambda w + w' \in f(\hat{V})$.

   /since $\hat{V}$ is a subspace (comes from "if"), $\lambda v + v' \in \hat{V}$ and thus, $\lambda w + w' \in f(\hat{V})$/

   Since also $f(0) = 0 \in f(\hat{V})$, it follows that $f(\hat{V})$ is a subspace.

   /as $\hat{V}$ is a subspace $0 \in \hat{V}$ and $f(0) = 0$ (linearity of $f$) hence $0 \in f(\hat{V})$/

b. Let $v, v' \in f^{-1}(\hat{W})$ and $\lambda \in \mathbb{F}$.

   /defining tools for subspace criterion, in this case for $f^{-1}(\hat{W})$ (preimage of $\hat{W}$ under $f^{-1}$)/

   Then $f(v), f(v') \in \hat{W}$, and therefore, $f(\lambda v + v') = \lambda f(v) + f(v') \in \hat{W}$,

   /letting $v, v' \in f^{-1}(\hat{W})$ strictly implies $f(v), f(v') \in \hat{W}$. linearity of $f$ lets $f(\lambda v + v') = \lambda f(v) + f(v')$ (which are elements of $\hat{W}$). since $\hat{W}$ is a subspace (by "if") it contains any linear combination $\lambda f(v) + f(v')$/

   since $\hat{W}$ is a subspace, and thus $\lambda v + v' \in f^{-1}(\hat{W})$.

   /since $\hat{W}$ is a subspace, $f(\lambda v + v') \in \hat{W}$ implies there must exist an element $(\lambda v + v') \in f^{-1}(\hat{W})$ (in a preimage)/

   We have $0 \in f^{-1}(\hat{W})$ because $f(0) = 0 \in \hat{W}$.

   /as $f(0) = 0 \in \hat{W}$, following the same logic, $0 \in f^{-1}(\hat{W})$, covering second part of subspace criterion/

   Therefore $f^{-1}(\hat{W})$ is a subspace.

c. Is a definition of surjectiveness.

d. If $f$ is injective, then the preimage of every singleton set has at most one element, so since $f(0) = 0$ it must be that $f^{-1}(\left\{ 0 \right\}) = \left\{ 0 \right\}$.

   /proof will be two sided, as proving if and only if/

   /first part of proof, pretty straight forward, if $f$ is injective, then every preimage element is "linked" to unique image element, hence, as $f(0) = 0$, it must be that the preimage of $0$ (im image) is $\left\{ 0 \right\}$ only/

   Now assume that $ker(f) = \left\{ 0 \right\}$.

   /second part of proof, assume kernel of $f$ is $\left\{ 0 \right\}$ only/

   Let $x, y \in V$ with $f(x) = f(y)$.

   /letting $x, y \in V$ with $f(x) = f(y)$ (because we will need to show $x = y$, key idea of injectiveness, no elements of preimage are mapped to the same element of image)/

   Then we obtain $0 = f(x) - f(y) = f(x - y)$, and hence $x - y \in ker(f)$, therefore $x - y = 0$, so $x = y$.

   /now we define $0$ in image through the difference of $f(x)$ and $f(y)$, and due to linearity of $f$, $f(x) - f(y) = f(x-y) = 0$, hence, $x-y$ must be element of $ker(f)$, and since kernel consist of only $\left\{ 0 \right\}$, $x$ must be equal to $y$/

   Thus $f$ is injective.

** Review Metrics
- Time Spent: Few hours.
- Confidence (1-5): 4
- Mistakes / Takeaways: Mistakes patched during annotations writing.

* Block C: Application/Testing
** Task
#+begin_quote
1. (6 points) Using elementary row operations, compute the inverse matrix of
   $$
   A=\left(\begin{array}{lll}
   3 & 2 & 0 \\
   3 & 1 & 3 \\
   2 & 3 & 1
   \end{array}\right) \in M_{3}\left(\mathbb{Z}_{5}\right)
   $$

2. Solve the following:
   a) (2 points) Define the notions kernel, image, and rank of a linear map.
   b) (2 points) State the dimension theorem (tn. rank-nullity theorem) for linear maps.
   c) (6 points) Prove the dimension theorem for linear maps. You do not have to prove additional theorems used in your proof, but you must clearly indicate (refer to) any theorems/propositions you use and state them precisely.
#+end_quote

** Solution

*** (1)

\begin{align*}
\left[ A \mid I \right] =
&\left[ \begin{array}{ccc|ccc}
3 & 2 & 0 & 1 & 0 & 0 \\
3 & 1 & 3 & 0 & 1 & 0 \\
2 & 3 & 1 & 0 & 0 & 1 \\
\end{array} \right] \\
\xrightarrow{m_{21} = 1, m_{31} = \frac{2}{3}}
&\left[ \begin{array}{ccc|ccc}
3 & 2           & 0 & 1             & 0 & 0 \\
0 & -1          & 3 & -1            & 1 & 0 \\
0 & \frac{5}{3} & 1 & -\frac{2}{3}  & 0 & 1 \\
\end{array} \right] \\
\xrightarrow{m_{32} = -\frac{5}{3}}
&\left[ \begin{array}{ccc|ccc}
3 & 2  & 0 & 1            & 0           & 0 \\
0 & -1 & 3 & -1           & 1           & 0 \\
0 & 0  & 6 & -\frac{7}{3} & \frac{5}{3} & 1 \\
\end{array} \right] \\
\xrightarrow{m_{23} = 3}
&\left[ \begin{array}{ccc|ccc}
3 & 2  & 0 & 1             & 0            & 0            \\
0 & -1 & 0 & \frac{1}{6}   & \frac{1}{6}  & -\frac{1}{2} \\
0 & 0  & 1 & -\frac{7}{18} & \frac{5}{18} & \frac{1}{6}  \\
\end{array} \right] \\
\xrightarrow{m_{23} = 2}
&\left[ \begin{array}{ccc|ccc}
3 & 0  & 0 & \frac{4}{3}   & \frac{1}{3}  & -1           \\
0 & 1  & 0 & -\frac{1}{6}  & -\frac{1}{6} & \frac{1}{2}  \\
0 & 0  & 1 & -\frac{7}{18} & \frac{5}{18} & \frac{1}{6}  \\
\end{array} \right] \\
&\left[ \begin{array}{ccc|ccc}
1 & 0  & 0 & \frac{4}{9}   & \frac{1}{9}  & -\frac{1}{3} \\
0 & 1  & 0 & -\frac{1}{6}  & -\frac{1}{6} & \frac{1}{2}  \\
0 & 0  & 1 & -\frac{7}{18} & \frac{5}{18} & \frac{1}{6}  \\
\end{array} \right] = \left[ I \mid A^{-1} \right]
\end{align*}


*** (2)

- (a)

  Let $T : V \rightarrow W$ be a linear map between vector spaces $V$ and $W$ over a field $\mathbb{F}$.

  - *Kernel*

    $$ker(T) = \left\{ v \in V : T(v) = 0_W \right\}$$

  - *Image*

    $$im(T) = \left\{ T(v) : v \in V \right\} = T(V)$$

  - *Rank*

    $$rank(T) = dim(im(T))$$

- (b)

  Let $V$ be finite dimensional vector space and $f : V \rightarrow W$ be linear. Hence,

  $$dim(V) = dim(ker(f)) + dim(im(f))$$

- (c)

  Let $dim(V) = n, \, dim(ker(f)) = k$.

  1. Basis extension

     Choose basis $\left\{ b_1, \ldots, b_k \right\}$ for $ker(f)$. Extend basis $\left\{ b_1, \ldots, b_n \right\}$ for $V$.

  2. Claim

     The set $S = \left\{ f(b_{k+1}), \ldots, f(k_n) \right\}$ is basis for $im(f)$.

  3. Proof of span

     Let $y \in im(f)$. Hence, $\exists x \in V : y = f(x)$. Since $\left\{ b_1, \ldots, b_n \right\}$ is basis for $V$, we can write $x = \sum_{i=1}^n c_i b_i$. By linearity, and because $b_1, \ldots, b_k \in ker(f)$:

     $$y = f(\sum_{i=1}^n c_i b_i) = \sum_{i=1}^k c_i f(b_i) + \sum_{i=k+1}^n c_i f(b_i) = \sum_{i=k+1}^n c_i f(b_i)$$

     Thus, $S$ spans the $im(f)$.

  4. Proof of linear independence

     Assume $\sum_{i=k+1}^n c_i f(b_i) = 0$. By linearity $f(\sum_{i=k+1}^n c_i b_i) = 0$, meaning vector $v = \sum_{i=k+1}^n c_i + b_i$ is in $ker(f)$. Hence,

     Because $v \in ker(f)$, it can be expressed using the kernel's basis: $v = \sum_{i=1}^k c_i b_i$. Hence,

     $$\sum_{i=1}^k c_i b_i - \sum_{i=k+1}^n = 0$$

     Because $\left\{ b_1, \ldots, b_k \right\}$ is basis of $V$, all coefficients must be strictly zero. Therefore, $c_{k+1} = \ldots = c_n = 0$, proving $S$ is linearly independent.

  5. Conslusion

     Therefore, as $S$ spans $im(f)$ and is linearly independent, it is a basis of $im(f)$. Therefore,

     $$dim(V) = dim(ker(f)) + dim(im(f))$$

** Review Metrics
- Time Spent:
- Confidence (1-5):
- Mistakes / Takeaways:

