#+title: Functions
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-28>
#+lastmod: <2025-10-29 10:48>
#+options: num:t
#+startup: overview

* proofs by james cummings
** 8.1 Approaching functions
#+begin_quote
*Definition 8.1.* Given a pair of sets A and B, suppose that each element x ∈ A is associated, in some way, to unique element of B, which we denote f(x). Then f is said to be a function from A to B. This often denoted

        f : A -> B.

Furthermore, A is called the domain of f, and B is called the codomain of f. The set {f(x) : x ∈ A} is called the range of f.
#+end_quote

Little bit on terminology:

- Domain :: think of it as the inputs of f.
- Range :: as the outputs of f.
- Codomain :: as a possibly larger set in which all the outputs live.

In the end, all three are just sets, with some correspondence to each other via f.

Examples:

- f : ℝ -> ℤ where f(x) = floor(x).

  This is the floor function, where you just round down. E.g., floor(3,2) = 3, floor(-3,2) = -4.

- g : {1,2,3,4,5} -> {1,4,9,16,25,36,49} where g(x) = x^2.

  This is the usual square function, except that you can not plug anything besides 1,2,3,4,5 into g. For example, g(-2) and g(6) do not mean anything since g is only defined to accept elements from its domain. Notice that g's range is {1,4,9,16,25}.

** 8.2 Injections, Surjections and Bijections
#+begin_quote
*Definition 8.4.* A function f : A -> B is *injective* if f(a1) = f(a2) implies that a1 = a2.
#+end_quote

Basically, to be injective means that you do not have two arrows pointing at the same point.

- Example
  Injective (One-to-One) Function Example:
  For X={A, B, C} and Y={1, 2, 3}

  One possible injective map is -
  f(A) = 1, f(B) = 2, f(C) = 3.

  In this case, each element in set Y is mapped to by at most one element in set X.

  Non-Injective (Not One-to-One) Function Example:
  f: X → Y
  For X={A, B, C} and Y={1, 2}

  One possible non-injective map is -
  f(A) = 1, f(B) = 1, f(C) = 2.
    f: X → Y

#+begin_quote
*Definition 8.5.* A function f : A -> B is *surjective* if, for every b ∈ B, there exists some a ∈ A such that f(a) = b.
#+end_quote

#+begin_quote
When defining a function f : A -> B, the ideas of /existence/ and /uniqueness/ were focused on A - For every x ∈ A, we demanded that f(x) exist and be unique.

To be injective and surjective, the attention shifts to B. To be surjective means that B has an existence criterion (for every b ∈ B, there exists some a ∈ A that maps to it).

And to be injective means that B has a uniqueness-type criterion (for every b ∈ B, there is at most one a ∈ A that maps to it).
#+end_quote

#+begin_quote
*Definition 8.7.* A function f : A -> B is *bijective* if it is both injective and surjective.
#+end_quote

Being bijective means that every element in A is paired up with precisely one element of B.


*Proving x-jectiveness, for x ∈ {in, sur, bi}*

- *Injectiveness proof*
  #+begin_quote
  *Proposition.* f : A -> B is an injection.

  *Proof.* Assume x,y ∈ A and f(x) = f(y).

          - apply algebra,
          - logic, techniques

  Therefore, x = y.

  Since f(x) = f(y) implies x = y, f is injective.
  #+end_quote

  Alternatively, one could use the contrapositive, which would mean one starts by assuming x != y, and then concludes that f(x) != f(y).

- *Surjectiveness proof*
  #+begin_quote
  *Proposition.* f : A -> B is a surjection.

  *Proof.* Assume b ∈ B.

        - Magic to find an a ∈ A
        - where f(a) = b

  Since every b ∈ B has an a ∈ A where f(a) = b, f is surjective.
  #+end_quote

- *Example 8.8.*
  Let ℝ+ denote the nonnegative real numbers. Prove the following.

  a) f : ℝ -> ℝ where f(x) = x^2 is not injective, surjective or bijective.
     - *Solution*
       - What exactly does this function even mean?
         A function f(x) that takes any ℝ number, and returns the ℝ number f(x) = x^2.

       Since the f(x) = x^2 is a parabola, for every x ∈ ℝ+, such that f(x) ∈ ℝ+, there exists x ∈ ℝ-, such that f(x) ∈ ℝ+.

       #+begin_quote Injection proof
       *Proposition.* f(x) = x^2 : ℝ -> ℝ is not injection.

       *Proof.* Assume x,y ∈ ℝ and f(x) = f(y).

       Let x = 2, and y = -2.
       Thus, f(x) = 4; f(y) = 4.

       f(x) = 4 = f(y)
       While, x != y.

       Since, f(x) = f(y) does not imply x = y, f is not injective.
       #+end_quote

       #+begin_quote Surjection proof
       *Proposition.* f(x) = x^2 : ℝ -> ℝ is not surjection.

       *Proof.* Assume f(x) ∈ ℝ.

       Let f(x) = -4.

       Thus x = 2i.

       Since, x is not in the domain of the function, f is not surjective.
       #+end_quote

       #+begin_quote Bijection proof
       Since f is neither injective nor surjective, f is not bijective.
       #+end_quote

  b) f : ℝ+ -> ℝ where g(x) = x^2 is injective, but not surjective or bijective.
     - *Solution*
       Domain: ℝ+.
       Codomain: ℝ.

       #+begin_quote Injection proof
       *Proposition.* g : ℝ+ -> ℝ is injective.

       *Proof.* Assume x,y ∈ ℝ+ and g(x) = g(y). Then,

              g(x) = g(y)
               x^2 = y^2
       (x^2)^(1/2) = (y^2)^(1/2)

       In the reals, this gives two possibilities: x = y, x = -y. However, since we know that x,y ∈ ℝ+, the only option is that they are both positive, and so x = y. Thus, g is injective.

       Since g(x) = x^2 >= 0 for all x ∈ ℝ+, there does not exist and x ∈ ℝ for which g(x) = -4.

       #+end_quote

       #+begin_quote Surjection proof
       *Proposition.* g : ℝ+ -> ℝ is not surjective.

       *Proof.* Assume g(x) ∈ ℝ.

        Since g(x) = x^2 >= 0 for all x ∈ ℝ+, there does not exist and x ∈ ℝ for which g(x) = -4. And since -4 is in g's codomain, this proves g is not surjective.
       #+end_quote

       #+begin_quote Bijection proof
       *Proposition.* g : ℝ+ -> ℝ is not bijective.

       *Proof.* Since g is injective, but not surjective, g can not be bijective.
       #+end_quote

  c) f : ℝ -> ℝ+ where h(x) = x^2 is surjective, but not injective or bijective.

  d) f : ℝ+ -> ℝ+ where k(x) = x^2 is surjective, injective and bijective,
