#+title: Induction
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-09>
#+lastmod: <2025-10-11 15:53>
#+options: num:t
#+startup: overview

* 10.0 Introduction
Before we go straight to the induction proof technique, we should first look on what kind of statements it proves.

Lets consider this statement:
- `The sum of th efirst n odd natural numbers equals n^2.`

The below lines show what this conjecture says.
|-----+------------------------------------------+-------|
| *n* | *sum of the fisrt n odd natural numbers* | *n^2* |
|-----+------------------------------------------+-------|
| 1   | 1 = ...                                  | 1     |
| 2   | 1 + 3 = ...                              | 4     |
| 3   | 1 + 3 + 5 = ...                          | 9     |
| 4   | 1 + 3 + 5 + 7 = ...                      | 16    |
| 5   | 1 + 3 + 5 + 7 + 9 = ...                  | 25    |
| .   | .                                        | .     |
| .   | .                                        | .     |
| n   | 1 + 3 + 5 + 7 + 11 + ... + (2n - 1)= ... | n^2   |
| .   | .                                        | .     |
| .   | .                                        | .     |
|-----+------------------------------------------+-------|
We can see some patter that shows that conjecture might be true, however can not prove it with only this table.

Mathematical induction solves exactly this type of problems, which have an infinite list of statements S1, S2, S3, ... that we need to prove.

* 10.1 Proof by Induction
Outline for Proof by Indiction

#+begin_quote
*Proposition* The statement S1, S2, S3, S4, ... are all true.

Proof. (Induction)
1. Prove that the first statement S1 is true
2. Given any integer k >= 1, prove that the statement Sk => Sk+1 is true.

It follows by mathematical induction that every Sn is true.
#+end_quote

The first step is called a =basic step=, while the second step is called =inductive hypothesis=.

#+begin_quote
*Proposition* If n ∈ N, then 1 + 3 + 5 + 7 + ... + (2n - 1) = n^2.

Proof. We will prove this with mathematical induction.

1. Observe that if n = 1, this statement is 1 = 1^2, which is obviously true.
2. We must now prove Sk -> Sk+1, for any k >= 1.

   That is, we must show that ie 1 + 3 + 5 + 7 + ... + (2k - 1) = k^2, then 1 + 3 + 5 + 7 + ... + (2(k + 1) - 1) = (k + 1)^2.

   We use direct proof. Suppose 1 + 3 + 5 + 7 + ... + (2k - 1) = k^2. Then

                1 + 3 + 5 + 7 + ... + (2(k + 1) - 1) =
     1 + 3 + 5 + 7 + ... + (2k - 1) + (2(k + 1) - 1) =
   (1 + 3 + 5 + 7 + ... + (2k - 1)) + (2(k + 1) - 1) =
                                k^2 + (2(k + 1) - 1) = k^2 + 2k + 1
                                                     = (k + 1)^2
Thus 1 + 3 + 5 + 7 + ... + (2(k + 1) - 1) = (k + 1)^2. This proves that Sk => Sk+1.
It follows by induction that 1 + 3 + 5 + 7 + ... + (2k - 1) = k^2 for every n ∈ N.
#+end_quote

#+begin_quote
*proposition* if n is a non-negative integer, then 5|(n^5 - n).

proof. we will prove this with mathematical induction. observe that the first non-negative integer is 0, so the basis step involves 0.

1. if n = 0, this statement is 5|(0^5 - 0) or 5|0, which is obviously true.
2. let k >= 0. we need to prove that if 5|(k^5 - k), then 5|((k + 1)^5 - (k + 1)).

   we use direct proof. suppose 5|(k^5 - k). thus k^5 - k = 5a for some a ∈ z.

   observe that

   (k + 1)^5 - (k + 1) = k^5 + 5k^4 + 10k^3 + 10k^2 + 5k + 1 - k - 1
                       = (k^5 - k) + 5k^4 + 10k^3 + 10k^2 + 5k
                       = 5a + 5k^4 + 10k^3 + 10k^2 + 5k
                       = 5(a + k^4 + 2k^3 + 2k^2 + k)

this shows that (k + 1)^5 - (k + 1) is a multiple of 5, so 5|((k + 1)^5 - (k + 1)) is true.

we have now shown that 5|(k^5 - k) implies 5|((k + 1)^5 - (k + 1)).

it follows by induction that 5|(n^5 - n) for all non-negative integers n.
#+end_quote

#+begin_note
Note that both of the probelms are solved for ∀x ∈ N, Sn. Not for ∀x ∈ Z, Sn. Since for the last one you would also have to prove statements S0, S-1. S-2, ...
#+end_note


#+begin_note
=Just a little trick=

You know that you can add equla quantities to both sides of an equation without violating equality. But don't forget that you can also add /unequal/ quantities to both sides of /inequality/! This works as long as you add smaller quantity to the smaller side and bigger quantity to the bigger side.
#+end_note

#+begin_quote
*proposition* The inequality 2^n <= 2^(n+1) - 2^(n-1) - 1 holds for each n ∈ N

proof. We will prove this with mathematical induction

1. If n = 1, this statement is:
   2^1 <= 2^(1+1) - 2^(1-1) - 1  <=> 2 <= 4 - 1 - 1
   which is obviously true.
2. Say k >= 1. We use direct proof to show that 2^k <= 2^(k+1) - 2^(k-1) - 1 implies 2^(k+1) <= 2^((k+1)+1) - 2^((k+1)-1) - 1. Suppose 2^k <= 2^(k+1) - 2^(k-1) - 1. Then

   2^k <= 2^(k+1) - 2^(k-1) - 1
   2(2^k) <= 2(2^(k+1) - 2^(k-1) - 1)  (multiply both sides by 2)
   2^(k+1) <= 2^(k+2) - 2^k - 2
   2^(k+1) <= 2^(k+2) - 2^k - 2 + 1   (add 1 to the bigger side)
   2^(k+1) <= 2^(k+1+1) - 2^k - 1
   2^(k+1) <= 2^(k+1+1) - 2^(k+1-1) - 1

It follows by induction that 2^k <= 2^(k+1) - 2^(k-1) - 1 for each n ∈ N
#+end_quote

* 10.2 Proof by Strong Induction
Sometimes in an induction proof it is hard to show Sk implies Sk+1. It thus may be easier to show some "lower" Sm (with m < k) implies Sk+1.

For such situations, there is a slight variant of induction called =strong induction=.

Strong induction works just like the regular induction, except that in step 2 instead of assuming Sk is true and showing this forces Sk+1 to be true, we assume that all the statements S1, S2, S3, ... are true and show this forces Sk+1 to be true. The idea is that if the first k dominoes falling always forces the (k + 1)th domino to fall, then all the dominoes must fall.

Outline for Proof by Strong Induction
#+begin_quote
*Proposition* The statements S1, S2, S3, ... are all true.

Proof. (Strong induction)
1. Prove the first statement S1. (Or the first several Sn, if needed.)
2. Given any integer k > 1, prove (S1 ∧ S2 ∧ S3 ∧ ... ∧ Sk) => Sk+1.
#+end_quote

#+begin_quote
*Proposition* Any postage of 8c or more is possible using the 3c and 5c stamps.

Proof. We will use strong induction
1. This holds for postages of 8, 9, and 10 cents: For 8c, use one 3c and one 5c stamps. For 9c, three 3c. For 10c, two 5c.
2. Let k >= 10, and for each 8 <= m <= k, assume a postage of m cents can be obtained exactly with 3c and 5c stamps. (That assume statements S8, S9, ..., Sk are true.) We must show that Sk+1 is true, that is, (k+1) cents postage can be achieved with 3c and 5c stamps. By assumption, Sk-2 is true. Thus we can get (k-2)-cents postage with 3c and 5c stamps. Now just add one more 3c stamp and we have (k-2)+3 = k+1 cents postage with 3c and 5c.
#+end_quote

#+begin_quote
*Proposition* If n ∈ N, then 12|(n^4 - n^2)

Proof. We will prove this with strong induction.
1. First we note that the statement is true for the first six positive integers:
   For n = 1, 12 divides 1^4 - 1^2 = 0.         For n = 4, 12 divides 4^4 - 4^2 = 240.
   For n = 2, 12 divides 2^4 - 2^2 = 4.         For n = 5, 12 divides 5^4 - 5^2 = 600.
   For n = 3, 12 divides 3^4 - 3^2 = 72.        For n = 6, 12 divides 6^4 - 6^2 = 1260.
2. For k >= 6, assume 12|(m^4 - m^2) for 1 <= m <= k (i.e. S1, S2, ..., Sk are true). We must show Sk+1 is true, that is, 12|((k-5)^4 - (k-5)^2). To simplify, put k - 5 = l so 12|(l^4 - l^2), meaning l^4 - l^2 = 12a for a ∈ Z, and k + 1 = l + 6.

   (k + 1)^4 - (k + 1)^2 = (l + 6)^4 - (l + 6)^2
                         = l^4 + 24l^3 + 216l^2 + 864l + 1296 - (l^2 + 12l + 36)
                         = (l^4 - l^2) + 24l^3 + 216l^2 + 852l + 1260
                         = 12a + 24l^3 + 216l^2 + 852l + 1260
                         = 12(a + 2l^3 + 18l^2 + 71l + 105)
#+end_quote
