#+title: Problem Set 3
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-11>
#+lastmod: <2025-10-13 14:20>
#+options: num:t
#+startup: overview

* Weak Induction Structure
#+begin_quote
*Proposition.* S1, S2, S3, ..., are all true

*Base case.* "Demonstrate that S1 is true"

*Inductive hypothesis.* Assume that Sk is true.

*Induction step.* "Proof that Sk implies Sk+1"

*Conclusion.* Therefore, by induction, all the Sn are true.
#+end_quote

* Strong Induction Structure
#+begin_quote
*Proposition.* S1, S2, S3, ..., are all true

*Base case.* "Demonstrate that S1 (or more S) is true"

*Inductive hypothesis.* Assume that S1, S2, S3, ..., Sk are true.

*Induction step.* "Proof that (S1, S2, S3, ..., Sk) implies Sk+1 is true"

*Conclusion.* Therefore, by induction, all the Sn are true.
#+end_quote

* Problem 1
** Task
Prove that 3|(n^3 - n) for all n ∈ N

** Solution
*** Original
Proposition: 3|(n^3 - n) for all n ∈ N

Proof. I will prove this with mathematical induction.
1. If n = 1, this statement is 3|(1^3 - 1) or 3|0 which is obviously true.
2. let k > 0. I need to prove that if 3|(k^3 - k) implies 3|((k+1)^3 - (k+1))

   Suppose 3|(k^3 - k). Thus, k^3 - k = 3a for some a ∈ Z.

   Observe that:

   (k + 1)^3 - (k + 1) = k^3 + 3k^2 + 3k + 1 - k - 1
                       = (k^3 - k) + 3k^2 + 3k
                       = 3a + 3k^2 + 3k
                       = 3(a + k^2 + k)

This shows that (k + 1)^3 - (k + 1) is a multiple of 3, so 3|((k+1)^3 - (k+1)) is true.

I have just shown that 3|(k^3 - k) implies 3|((k+1)^3 - (k+1)).

It follows by induction that 3|(k^3 - k) for all n ∈ N.

*** Polished
Proposition: 3|(n^3 - n) for all n ∈ N.

Proof by induction on n.

Base case: n = 1. 1^3 - 1 = 0, and 3|0. So P(1) holds.

Inductive step: Assume for some k >= 1 that 3|(k^3 - k); i.e. k^3 - k = 3a for a ∈ Z. Then

(k + 1)^3 - (k + 1) = k^3 + 3k^2 + 3k + 1 - (k + 1)
                    = (k^3 - k) + 3k^2 + 3k

By the induction hypothesis (k^3 - k) = 3a, so

(k + 1)^3 - (k + 1) = 3a + 3k^2 + 3k
                    = 3(a + k^2 + k)

which is divisible by 3. Hence P(k) --> P(k+1). By induction the statement holds for all n >= 1.

*** Revision
*Proposition.* 3|(n^3 - n) for all n ∈ N.

*Basis case.* n = 1. 1^3 - 1 = 0 or 3|0. Statement holds.

*Inductive hypothesis.* Assume 3|(k^3 - k) for k ∈ N.

*Induction step.* (k^3 - k) = 3a, a ∈ N0.
                  k^3 - k = 3a

                  (k+1)^3 - (k + 1) = k^3 + 3k^2 + 3k + 1 - k - 1
                                    = (k^3 - k) + 3k^2 + 3k + 1 - 1
                                    = 3a + 3k^2 + 3k
                                    = 3(a + k^2 + k)

*Conclusion.* Therefore by induction, 3|(n^3 - n) for all n ∈ N.

* Problem 2
** Task
Prove that 2^n < n! for all n >= 4.

** Solution
*** Original
Proposition: 2^n < n! for all n >= 4.

Proof by induction on n.

Base case: n = 4. 2^4 = 8 and 4! = 24. Thus, 8 < 24. So P(4) holds.

Inductive step: Assume for k >= 4 that 2^k < k!. Then

2^(k+1) < 2 * k!

But for k >= 4, we have k + 1 >= 5 > 2, hence

2 * k! < (k + 1) * k! = (k+1)!

Thus, combining two inequalities, it gives:

2^(k+1) < (k+1)!

It follows by the induction that 2^n < n! for all n >= 4.

*** Revision
*Proposition.* 2^n < n! for all n >= 4.

*Base case.* n = 4. 2^4 < 4! <--> 16 < 24. Statement holds.

*Inductive hypothesis.* Assume 2^k < k! for k >= 4.

*Induction step.* 2^k < k! (multiply by 2)
                  2 * 2^k < 2 * k!
                  2^(k+1) < 2 * k!

                  since k + 1 >= 5, thus k + 1 > 2

                  2^(k+1) < (k + 1) * k!
                  2^(k+1) < (k + 1)!

*Conclusion.* Therefore, by induction, 2^n < n! for all n >= 4.

* Problem 3 [check again]
** Task
Prove that sin(nx) <= n * sin(x) for all x ∈ R and n ∈ N.

** Solution
Proposition: sin(nx) <= n * sin(x) for all x ∈ R and n ∈ N.

Proof by induction.

Base case: n = 1. sin(1 * x) <= 1 * sin(x), x ∈ R. So P(1) holds.

Inductive step: Assume for k >= 1 that sin(kx) <= k * sin(x) for all n ∈ N. Then

/Trig. identity: sin(A + B) = sin(A)cos(B) + cos(A)sin()B./

sin((k+1)x) <= (k + 1) * sin(x)
sin(x + kx) <= ksin(x) + sin(x)
sin(x)cos(kx) + cos(x)sin(kx) <= ksin(x) + sin(x)

Because cos(kx) <= 1 for x ∈ R and sin(x) >= 0, we have cos(kx)sin(x) <= 1 * sin(x) = sin(x).

Also cos(x) <= 1, so

sin(kx)cos(x) <= ksin(x) + sin(x) = (k + 1)sin(x)

Thus, P(k) --> P(k+1). By the induction the inequality holds for all n ∈ R.

* Problem 4
** Task
(Bernoulli inequality.) Prove that (1 + x)^n >= 1 + nx for all real x >= -1 and all n ∈ N.

** Solution
*** Original
- Bernoulli inequality is basically what we are proving here.

Proposition: Prove that (1 + x)^n >= 1 + nx for all real x >= -1 and all n ∈ N.

Proof by induction.

Basis case: n = 1. (1 + x)^n >= 1 + 1*x  <--> 1 + x = 1 + x. Thus P(1) holds.

Inductive step: Assume that (1 + x)^k >= 1 + kx for some k >= 1. Since x >= -1, we have 1 + x >= 0, so multiplying inequality by (1 + x) gives:

(1 + x)^k >= 1 + kx  (multiply by (1 + x))
(1 + x)^(k + 1) >= (1 + kx)(x + 1)
(1 + x)^(k + 1) >= x(k + 1) + 1 + x^2 * k

Since k >= 1 and x >= -1 --> k * x^2 >= 0

Therefore, we can drop non-negative term from the smaller side.

(1 + x)^(k + 1) >= x(k + 1) + 1

Hence, this shows that P(k) --> P(k+1). By induction the statement holds for all n ∈ N.
*** Revision
*Proposition.* (1 + x)^n >= 1 + nx for all real x >= -1 and all n ∈ N.

*Basis case.* n = 1. (1 + x)^1 >= 1 + 1 * x <--> 1 + x >= 1 + x. Statement holds.

*Inductive hypothesis.* Assume (1 + x)^k >= 1 + kx, for x ∈ R, x >= -1, k ∈ N.

*Induction step.* (1 + x)^k >= 1 + kx  (multiply by (1 + x))
                  (1 + x)^(k+1) >= (1 + kx)(1 + x)
                  (1 + x)^(k+1) >= 1 + x + kx + kx^2
                  (1 + x)^(k+1) >= x(1 + k) + 1 + kx^2
                  (1 + x)^(k+1) >= 1 + x(k+1) + kx^2  (since x^2 and k ∈ N, kx^2 >= 0)
                  (1 + x)^(k+1) >= 1 + x(k+1)

*Conclusion.* Therefore, by induction, (1 + x)^k >= 1 + kx, for x ∈ R, x >= -1, k ∈ N.

* Problem 5
** Solution
1/k(k+1) = 1/k - 1/k+1

Thus

P(k) = (1/1 - 1/2) + (1/2 - 1/3) + (1/3 - 1/4) + ... + (1/k - 1/k+1)
P(k) = 1/1 - 1/2 + 1/2 - 1/3 + 1/3 - 1/4 + ... + 1/k - 1/k+1
P(k) = 1/1 - 1/k+1

* Problem 6
** Task
Let S be a set containing n elements. Use induction to prove that |P(S)| = 2^n.

** Solution
*** Original
*Proposition.* Let S be a set containing n elements. Use induction to prove that |P(S)| = 2^n.

*Base case.* n = 0, |P(S)| = 2^0 = 1. It is obviously true. Base holds.

*Inductive hypothesis.* Suppose for some n >= 0 the statement holds: for every set with n elements has 2^n subsets.

*Induction step.* Let S be any set with n + 1 elements. Pick a particular element a ∈ S and write T := S \ {a}. Then |T| = n. Every subset of S either contains a or does not. So partition P(S) into:

- A = {X ⊆ S: a ∉ X}
- B = {X ⊆ S: a ∈ X}

But A is exactly P(T), so by the induction hypothesis |A| = 2^n. Define

f: P(T) -> B,   f(X) = X ∪ {a}

S = {∅, 1, 2, 3}
P(S) = {∅}, {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}

let a = 3

T = {∅, 1, 2}

A = {∅}, {1}, {2}, {1, 2}
B = {3}, {1, 3}, {2, 3}, {1, 2, 3}

Since B is a bijection of the A, |B| = 2^n.

Thus, |P(S)| = |A| + |B| = 2^n + 2^n = 2^(n + 1)

*Conclusion.* Therefore, by the induction, |P(S)| = 2^n.

* Problem 7
** Task
The bank has an unlimited supply of 3 and 5 euros bills. Prove that it can dispense any number of euros greater than 8 (without change).

** Solution
*** Original
8 = 3 * 1 + 5 * 1       10 = 3 * 0 + 5 * 2      12 = 3 * 4 + 5 * 0      14 = 3 * 3 + 5 * 1
9 = 3 * 3 + 5 * 1       11 = 3 * 2 + 5 * 1      13 = 3 * 1 + 5 * 2      15 = 3 * 0 + 5 * 3

*Proposition.* If n ∈ R, n >= 8, then n = 3a + 5b, where a,b ∈ Z; a,b >= 0.

*Base cases.* In the induction step I will need 3 cases prior. Therefore
              Let a = 1, b = 1, then 3 * 1 + 5 * 1 = 8.
              Let a = 1, b = 1, then 3 * 3 + 5 * 0 = 9.
              Let a = 1, b = 1, then 3 * 0 + 5 * 2 = 10.
              Base holds.

*Inductive hypothesis.* Assume that for some integer k >= 10, the result holds for
                        n = 10, 11, ..., k.

*Induction step.* I aim to prove the result for k + 1. By the inductive hypothesis.

I must show k + 1 has the same form.

(k + 1) - 3 = k - 2

Since k >= 10, we have k - 2 >= 8. By the inductive hypothesis k - 2 = 3a + 5b

k + 1 = 3 + (k − 2) = 3 + (3a + 5b) = 3(a + 1) + 5b

*Conclusion.* Because the base cases 8, 9, 10 hold, and an inductive step works for every k >= 10, by strong induction, every integer n >= 8 can be written in the form of 3a + 5b, whith a,b ∈ Z; a,b >= 0.

*** Revision
*Proposition.* If n ∈ R, n >= 8, then n = 3a + 5b, where a,b ∈ Z; a,b >= 0.

*Base cases.* 8 = 3 * 1 + 5 * 1
              9 = 3 * 3 + 5 * 0
              10 = 3 * 0 + 5 * 2
              Base holds.

*Inductive hypothesis.* Assume k ∈ R, k >= 8, then k = 3a + 5b, where a,b ∈ Z; a,b >= 0.

*Induction step.* k = 3a + 5b
                  k + 3 = 3a + 5b + 3
                  k + 3 = 3(a + 1) + 5b

                  This shows that k + 3 can be expressed as the sum of 3s and 5s, where the number 3s has increased by one.

*Conlcusion.* Since the statement is true for the base cases, and the induction step shows that P(k) --> P(k+3), the statement is true for k >= 8.

* Problem 8
** Task
There is a 16 × 16 chess board with one square removed. Prove that it can be tiled using triminoes (you can rotate them). We have already proved it in class, and now your goal is to express the proof in words.

** Solution
Chess board follows the resolution of 2^n x 2^n.

*Base case.* The base case is when n = 1, and among the four possible squares that one can remove from a 2x2 chessboard, each leaves a chessboard which can be perfectly covered by the single L shaped tile.

*Inductive hypothesis.* Let k ∈ N, and assume that if any one square is removed from a 2^k x 2^k chessboard, the result can be perfectly covered with L shaped tiles.

*Induction step.* Consider 2^(k+1) x 2^(k+1) chessboard with any one square removed. Cut this chessboard in half vertically and horisontally to form 2^k x 2^k chessboards. One of these four will have a square removed and hence by the induction hypothesis can be perfectly covered.

Next place a single L shaped tile so that it covers one from each of the other three 2ˆk x 2^k chessboards.

Each of these other 2^k x 2ˆk chessboards can be perfectly covered by the inductive hypothesis, and hence 2^(k+1) x 2^(k+1) chessboard can be perfecly covered.

*Conclusion.* By induction, for every n ∈ N, if any one square is removed from a 2^n x 2^n chessboard, the result can be perfectly covered with L shaped tiles.

* Problem 9
** Task
Prove that there exists an n ∈ N for which 11|(2^n − 1).

** Solution
** Solution
#+begin_src julia :results output
k = 1

function S(n::Int)
    return powermod(2, n, 11) == 1   # (2^n - 1) % 11 == 0  <=> 2^n % 11 == 1
end

while true
    global k
    if S(k)
        println(k)
        break
    end
    k += 1
end
#+end_src

#+RESULTS:
: 1
: S (generic function with 1 method)
: 10

Therefore, 11|(2^n - 1) where n = 10.
