#+title: Direct Proof
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-13>
#+lastmod: <2025-10-17 16:01>
#+options: num:t
#+startup: overview

* book of proof
** 4.0 Introduction
- Theorem :: is a mathematical statement that is true and can be (and has been) verified as true.
- Proof :: of a theorem is a written verification that shows that the theorem is definitely and unequivocally true.
- Definition :: is an exact, unambigious explanation of the meaning of a mathematical word or phrase.

** 4.1 Theorems
Examples of theorem:

- *Theorem* - Let f be differentiable on an open interval I and let c ∈ I. If f(c) is the maximum or minimum value of f on I, then f(c) = 0.
- *Theorem* - Suppose f is continious on the interval [a, b]. Then f is integrable on [a, b].
- *Theorem* - Every absolutely convergent series converges.

Observe that in each of these theorems either has the conditional form "If P, then Q." or can be put into that form.

* proofs james cumings
** 2.1 Working from Definitions
#+begin_quote Definition 1.1
- An integer n is even if n = 2k for some integer k;
- An integer n is odd if n = 2k + 1 for some integer k.
#+end_quote

#+begin_quote Fact 1.1
The sum of integers is an integer, the difference of integers is an integer, and the product of integers is an integer. Also, every integer is either even or odd.
#+end_quote

#+begin_quote
*Proposition.* The sum of two even integers is even.

*Proof.* Assume that n and m are even integers. By Definition 1.1 this means that n = 2a and m = 2b, for some integers a and b. Then,

n + m = 2a + 2b = 2(a + b).

And since, by Fact 1.1, a + b is an integer too, we have shown that n + m = 2k, where k = a + b is an integer. Therefore, by Definition 1.1, this means that n + m is even.
#+end_quote

#+begin_quote
*Proposition.* The sum of two odd integers is even.

*Proof.* Assume that n and m are odd integers. By Definition 1.1, this means that n = 2a + 1 and m = 2b + 1, for some integers a and b. Then,

n + m = (2a + 1) + (2b + 1) = 2a + 2b + 2 = 2(a + b + 1)

And since, by fact 1.1, a + b + 1 is an integer too, we have shown that n + m = 2k, where k = a + b + 1 is an integer. Therefore,  by Definition 1.1, this means that n + m is even.
#+end_quote

#+begin_quote
*Proposition.* If n is an odd integer, then n^2 is an odd integer.

*Proof.* Assume that n is an odd integer. By Definition 1.1 this means that n = 2a + 1, for some integer a. Then,

n^2 = (2a + 1)^2 = 4a^2 + 4a + 1 = 2(2a + 2a) + 1.

And since, by Fact 1.1 2a^2 + 2a = 2 * a * a + 2 * a is an integer too, we have shown that n^2 = 2k + 1, where k = 2a^2 + 2a is an integer. Therefore, by Definition 1.1 this means that n^2 is odd.
#+end_quote


#+begin_quote
*Proposition.* P --> Q

*Proof.* Assume P.

"An explanation of what P means" <--- Apply definitions and/or other results.
- apply algebra, logic, techniques
"Hey look, that's what Q means"

Therefore Q.
#+end_quote

** 2.2 Proofs by Cases
The proof by cases is a "divide and conquer" strategy where one breaks up their work into two or more cases.

#+begin_quote
*Proposition.* If n is an integerm then n^2 + n + 6 is even.

*Proof idea.* The idea lies in the principle of dividing the possible values of n into odd and even numbers.

*Proof.* Assume that n is an integer. Then n is either even or odd.

Case 1: n is even. Then n = 2a for some integer a. Thus,

n^2 + n + 6 = (2a)^2 + (2a) + 6
            = 4a^2 + 2a + 6
            = 2(2a^2 + a + 3).

and since a is an integer, 2a^2 + a + 3 is also an integer. Therefore, n^2 + n + 6 = 2k, where k = 2a^2 + a + 3 is an integer, which is by the definition of an even integer means that n^2 + n + 6 is even.

Case 2: n is odd. Then n = 2a + 1 for some integer a. Thus,

n^2 + n + 6 = (2a + 1)^2 + (2a + 1) + 6
            = 4a^2 + 4a + 1 + 2a + 1 + 6
            = 4a^2 + 6a + 8
            = 2(2a^2 + 3a + 4).

and since a is an integer, 2a^2 + 3a + 4 is also an integer. Therefore, n^2 + n + 6 = 2k, where k = 2a^2 + 3a + 4 is an integer, which is by the definition of an even integer means that n^2 + n + 6 is even.

I have shown that n^2 + n + 6 is even whether n is even or odd. Combined, this shows that n^2 + n + 6 is even for all integers n, completing the proof.
#+end_quote

Here are 3 examples that I might encounter in the future:

1. Case 1: n is prime
   Case 2: n is composite

2. Case 1: f is continious
   Case 2: f is not continious

3. Case 1. n ≡ 0 (mod 3)
   Case 2. n ≡ 1 (mod 3)
   Case 3. n ≡ 2 (mod 3)

** 2.3 Divisibiility
To start of, what does it mean to say that one integer /divides/ another?

So, one can define it as:

#+begin_quote
"a divides b" if b/a is an integer.
#+end_quote

better definition is:
#+begin_quote
"a divides b" if b/a = k where k is an integer.
#+end_quote

and even better definition is:
#+begin_quote
"a divides b" if b = ka where k is an integer.
#+end_quote


#+begin_quote
*Definition 2.8* An integer a is said to divide an integer b if b = ak for some integer k. When a does divide b, we write "a | b" and when a does not divide b we write "a∤b"
#+end_quote

#+begin_note
A common mistake is to see something like "2 | 8" and think that this is equals to 4. The expression "a | b" is either true or false, it never equals to a number. 2 | 8 is true, while 3 | 8 is false.
#+end_note



#+begin_quote
*Proposition. 2.10* Let a, b and c be integers. If a|b and b|c, then a|c.

*Scratch work.*

- If we choose a = 3, b = 12 and c = 24, then it is indeed true that 3|12 and 12|24. According to this proposition, it must then be true that 3|24, and indeed its true.
- If we choose a = 8, b = 16 and c = 32, then it is also true, since 8|16, 16|32 and 8|32.

*Proof.* Assume that a, b and c are integers, and a|b and b|c.
Then by the definition of divisibility, b = as for some integer s, and c = bt for some integer t. Thus,
c = bt
  = (as)t
  = a(st).

I have shown that c = a(st), and since s and t are integers, so is st. SO it is indeed true that c = ak for some integer k = st, which by the definition of divisibility means a|c.
#+end_quote

** 2.4 Greatest Common Divisors
#+begin_quote
*Definition 2.12* Let a and b be integers. If c|a and c|b, then c is said to be a common divisor of a and b.
The greatest common divisor of a and b is the largest integer d such that d|a ad d|b. This number is denoted as gcd(a,b).
#+end_quote

First observe that since 1|a and 1|b, the greatest common divisor always exists and is always at least 1. Below are some examples.
- gcd(6, 8) = 2
- gcd(6, -8) = 2
- gcd(-5, -20) = 5
- gcd(12, 8) = 4
- gcd(7, 15) = 1
- gcd(9, 9) = 9

#+begin_quote
*Theorem 2.13* (Bezout's identity). If a and b are positive integers, then there exist integer k and l such that

gcd(a, b) = ak + bl
#+end_quote

Just to make sure I understood this, lets jump down an example. Maybe a = 12 and b = 20, making gcd(12, 20) = 4. The claim is that there are integers k and l such that

gcd(12, 20) = 12k + 20l

Indeed, gcd(12, 20) = 4, and by testing a few numbers one can find that

4 = (12)(2) + (20)(-1).

or maybe like this

4 = (12)(-3) + (20)(2).

There are infinitely many solutions! But how do we prove it???

This will be our general structure:

1. Assume a and b are positive integers. These should be thought of as fixed numbers (like a = 12 and b = 20), which means that gcd(a,b) is also a fixed numebr (like gcd(a, b) = 4). But depsite being fixed, we don't know what they are. What we get to control is the k and l - we want to choose those in such a way that gcd(a, b) = ak + bl.

2. As it turns out, there is a clever way to choose the correct k and l. But once we pick the correct k and l, we still have to prove that they work. Once we choose them, the sum ak + bl will be equal to something (we will call this sum d; that is, d = ak + bl), and then the goal turns to proving that d is what want: We need to show d = gcd(a, b).

3. To show that d is in fact gcd(a, b), we will use the definition of the greatest common divisor. Once we accomplish this, then d = ak + bl from the previous step will turn into gcd(a, b) = ak + bl, completing the proof.

** 2.5 Modular Arithmetics
When dividing integer a by an integer m, the relationship between a and its remainder is surprisingly important. In fact, in such a case we say that a is a congruent to its remainder.

#+begin_quote
*Definition 2.14.* For integers a, r, and m we say that a is congruent to r modulo m and we write a ≡ r (mod m) if m|(a-r).
#+end_quote

Some examples:
- 18 ≡ 4 (mod 7)
- 13 ≡ 1 (mod 3)
- 3 ≡ 3 (mod 13)
- 35 ≡ 0 (mod 5)
- -3 ≡ 2 (mod 5)
- -15 ≡ 1 (mod 2)

#+begin_quote
*Proposition 2.15* (Properties fo Modular Arithmetics). Assume that a, b, c, d and m are integers, a ≡ b (mod m) and c ≡ d (mod m). Then,

1. a + c ≡ b + d (mod m);
2. a - c ≡ b - d (mod m);
3. a * c ≡ b * d (mod m).

1. a + c ≡ b + d (mod m).
   *Proof.* Assume a ≡ b (mod m); c ≡ d (mod m); a,b,c,d,m ∈ Z.
            Thus,
            a = km + b; c = jm + d; k,j ∈ Z.
            a + c = m(k + j) + (b + d)

            Therefore, since m divides (a + c) - (b + d) = m(k + j), we have a congruence.
            (a + c) ≡ (b + d) (mod m)

2. a - c ≡ b - d (mod m)
   *Proof.* Assume a ≡ b (mod m); c ≡ d (mod m); a,b,c,d,m ∈ Z.
            Thus,
            a = km + b; c = jm + d; k,j ∈ Z.
            (a - c) = m(k - j) + (b - d)

            Therefore, since m divides (a - c) - (b - d) = m(k - j), we have a congruence.
            (a - c) ≡ (b - d) (mod m)

3. a * c ≡ b * d (mod m).
   *Proof.* Assume a ≡ b (mod m); c ≡ d (mod m); a,b,c,d,m ∈ Z.
            Thus,
            a = km + b; c = jm + d; k,j ∈ Z.
            (a * c) = (km + b)(jm + d)
            ac = kjm^2 + (dk + bj)m + bd
            ac - bd = m(kjm + dk + bj) which is divisible by m.

            Therefore, since m divides (a * c) - (b * d) = m(kjm + dk + bj), we have a congruence.
            (a * c) ≡ (b * d) (mod m)
#+end_quote

#+begin_quote
*Definition 2.16.* A integer p >= 2 is prime if its only positive divisors are 1 and p. An integer n >= 2 is a composite is its is not prime. Equivalently, n is composite if it can be written as n = st, where s and t are integers and 1 < s <= t < n
#+end_quote

#+begin_quote
*Lemma 2.17.* Let a, b and c be integers, and let p be a prime.

1. If p !| a, then gcd(p,a) = 1.
2. if a | bc and gcd(a,b) = 1, then a | c.
3. if p | bc, then p | b or p | c (or both).
#+end_quote

*Proof Idea for 1.* The divisors of p are p, -p, 1 and -1. Therefore, these four numbers are the only possible common divisors between p and a. The question is: Which of these also divides a? And among ones which do, which is targest?

|---------+---------+---------+---------|
| *-p*    | *-1*    | *1*     | *p*     |
|---------+---------+---------+---------|
| is not  | is a    | is a    | is not  |
| common  | common  | common  | common  |
| divisor | divisor | divisor | divisor |
| with a  | with a  | with a  | with a  |
|---------+---------+---------+---------|
Along the two which are common divisors, we can see that 1 is the greatest.

*Proof Idea for 2.* In this part we need a tool. A tool that connects integers to their gcd ... and Bezout's identity will do just that!

*Proof Idea for 2.* Part 3 turns out to be just a mixture of parts 1 and 2. So once those are proven, we will ba able to unite their powers to give us.

#+begin_quote
*Proof.* Assume that a, b, c are integers, and p is a prime.

*Proof of 1.* Assume that p does not divide a. To be a common divisor of a an dp means that you mist divide both of them, but since we are assuming taht n does not divide a, this also means taht p is not a common divisor of a and p. And since p is not a common divisor of a and o
#+end_quote
