#+title: Direct Proof
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-13>
#+lastmod: <2025-10-15 09:15>
#+options: num:t
#+startup: overview

* book of proof
** 4.0 Introduction
- Theorem :: is a mathematical statement that is true and can be (and has been) verified as true.
- Proof :: of a theorem is a written verification that shows that the theorem is definitely and unequivocally true.
- Definition :: is an exact, unambigious explanation of the meaning of a mathematical word or phrase.

** 4.1 Theorems
Examples of theorem:

- *Theorem* - Let f be differentiable on an open interval I and let c ∈ I. If f(c) is the maximum or minimum value of f on I, then f(c) = 0.
- *Theorem* - Suppose f is continious on the interval [a, b]. Then f is integrable on [a, b].
- *Theorem* - Every absolutely convergent series converges.

Observe that in each of these theorems either has the conditional form "If P, then Q." or can be put into that form.

* proofs james cumings
** 2.1 Working from Definitions
#+begin_quote Definition 1.1
- An integer n is even if n = 2k for some integer k;
- An integer n is odd if n = 2k + 1 for some integer k.
#+end_quote

#+begin_quote Fact 1.1
The sum of integers is an integer, the difference of integers is an integer, and the product of integers is an integer. Also, every integer is either even or odd.
#+end_quote

#+begin_quote
*Proposition.* The sum of two even integers is even.

*Proof.* Assume that n and m are even integers. By Definition 1.1 this means that n = 2a and m = 2b, for some integers a and b. Then,

n + m = 2a + 2b = 2(a + b).

And since, by Fact 1.1, a + b is an integer too, we have shown that n + m = 2k, where k = a + b is an integer. Therefore, by Definition 1.1, this means that n + m is even.
#+end_quote

#+begin_quote
*Proposition.* The sum of two odd integers is even.

*Proof.* Assume that n and m are odd integers. By Definition 1.1, this means that n = 2a + 1 and m = 2b + 1, for some integers a and b. Then,

n + m = (2a + 1) + (2b + 1) = 2a + 2b + 2 = 2(a + b + 1)

And since, by fact 1.1, a + b + 1 is an integer too, we have shown that n + m = 2k, where k = a + b + 1 is an integer. Therefore,  by Definition 1.1, this means that n + m is even.
#+end_quote

#+begin_quote
*Proposition.* If n is an odd integer, then n^2 is an odd integer.

*Proof.* Assume that n is an odd integer. By Definition 1.1 this means that n = 2a + 1, for some integer a. Then,

n^2 = (2a + 1)^2 = 4a^2 + 4a + 1 = 2(2a + 2a) + 1.

And since, by Fact 1.1 2a^2 + 2a = 2 * a * a + 2 * a is an integer too, we have shown that n^2 = 2k + 1, where k = 2a^2 + 2a is an integer. Therefore, by Definition 1.1 this means that n^2 is odd.
#+end_quote


#+begin_quote
*Proposition.* P --> Q

*Proof.* Assume P.

"An explanation of what P means" <--- Apply definitions and/or other results.
- apply algebra, logic, techniques
"Hey look, that's what Q means"

Therefore Q.
#+end_quote

** 2.2 Proofs by Cases
The proof by cases is a "divide and conquer" strategy where one breaks up their work into two or more cases.

#+begin_quote
*Proposition.* If n is an integerm then n^2 + n + 6 is even.

*Proof idea.* The idea lies in the principle of dividing the possible values of n into odd and even numbers.

*Proof.* Assume that n is an integer. Then n is either even or odd.

Case 1: n is even. Then n = 2a for some integer a. Thus,

n^2 + n + 6 = (2a)^2 + (2a) + 6
            = 4a^2 + 2a + 6
            = 2(2a^2 + a + 3).

and since a is an integer, 2a^2 + a + 3 is also an integer. Therefore, n^2 + n + 6 = 2k, where k = 2a^2 + a + 3 is an integer, which is by the definition of an even integer means that n^2 + n + 6 is even.

Case 2: n is odd. Then n = 2a + 1 for some integer a. Thus,

n^2 + n + 6 = (2a + 1)^2 + (2a + 1) + 6
            = 4a^2 + 4a + 1 + 2a + 1 + 6
            = 4a^2 + 6a + 8
            = 2(2a^2 + 3a + 4).

and since a is an integer, 2a^2 + 3a + 4 is also an integer. Therefore, n^2 + n + 6 = 2k, where k = 2a^2 + 3a + 4 is an integer, which is by the definition of an even integer means that n^2 + n + 6 is even.

I have shown that n^2 + n + 6 is even whether n is even or odd. Combined, this shows that n^2 + n + 6 is even for all integers n, completing the proof.
#+end_quote

Here are 3 examples that I might encounter in the future:

1. Case 1: n is prime
   Case 2: n is composite

2. Case 1: f is continious
   Case 2: f is not continious

3. Case 1. n ≡ 0 (mod 3)
   Case 2. n ≡ 1 (mod 3)
   Case 3. n ≡ 2 (mod 3)

** 2.4 Divisibiility
