#+title: Induction
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-09>
#+lastmod: <2025-10-10 16:08>
#+options: num:t
#+startup: overview

* 10.0 Introduction
Before we go straight to the induction proof technique, we should first look on what kind of statements it proves.

Lets consider this statement:
- `The sum of th efirst n odd natural numbers equals n^2.`

The below lines show what this conjecture says.
|-----+------------------------------------------+-------|
| *n* | *sum of the fisrt n odd natural numbers* | *n^2* |
|-----+------------------------------------------+-------|
| 1   | 1 = ...                                  | 1     |
| 2   | 1 + 3 = ...                              | 4     |
| 3   | 1 + 3 + 5 = ...                          | 9     |
| 4   | 1 + 3 + 5 + 7 = ...                      | 16    |
| 5   | 1 + 3 + 5 + 7 + 9 = ...                  | 25    |
| .   | .                                        | .     |
| .   | .                                        | .     |
| n   | 1 + 3 + 5 + 7 + 11 + ... + (2n - 1)= ... | n^2   |
| .   | .                                        | .     |
| .   | .                                        | .     |
|-----+------------------------------------------+-------|
We can see some patter that shows that conjecture might be true, however can not prove it with only this table.

Mathematical induction solves exactly this type of problems, which have an infinite list of statements S1, S2, S3, ... that we need to prove.

* 10.1 Proof by Induction
Outline for Proof by Indiction

#+begin_quote
*Proposition* The statement S1, S2, S3, S4, ... are all true.

Proof. (Induction)
1. Prove that the first statement S1 is true
2. Given any integer k >= 1, prove that the statement Sk => Sk+1 is true.

It follows by mathematical induction that every Sn is true.
#+end_quote

The first step is called a =basic step=, while the second step is called =inductive hypothesis=.

#+begin_quote
*Proposition* If n ∈ N, then 1 + 3 + 5 + 7 + ... + (2n - 1) = n^2.

Proof. We will prove this with mathematical induction.

1. Observe that if n = 1, this statement is 1 = 1^2, which is obviously true.
2. We must now prove Sk -> Sk+1, for any k >= 1.

   That is, we must show that ie 1 + 3 + 5 + 7 + ... + (2k - 1) = k^2, then 1 + 3 + 5 + 7 + ... + (2(k + 1) - 1) = (k + 1)^2.

   We use direct proof. Suppose 1 + 3 + 5 + 7 + ... + (2k - 1) = k^2. Then

                1 + 3 + 5 + 7 + ... + (2(k + 1) - 1) =
     1 + 3 + 5 + 7 + ... + (2k - 1) + (2(k + 1) - 1) =
   (1 + 3 + 5 + 7 + ... + (2k - 1)) + (2(k + 1) - 1) =
                                k^2 + (2(k + 1) - 1) = k^2 + 2k + 1
                                                     = (k + 1)^2
Thus 1 + 3 + 5 + 7 + ... + (2(k + 1) - 1) = (k + 1)^2. This proves that Sk => Sk+1.
It follows by induction that 1 + 3 + 5 + 7 + ... + (2k - 1) = k^2 for every n ∈ N.
#+end_quote

#+begin_quote
*proposition* if n is a non-negative integer, then 5|(n^5 - n).

proof. we will prove this with mathematical induction. observe that the first non-negative integer is 0, so the basis step involves 0.

1. if n = 0, this statement is 5|(0^5 - 0) or 5|0, which is obviously true.
2. let k >= 0. we need to prove that if 5|(k^5 - k), then 5|((k + 1)^5 - (k + 1)).

   we use direct proof. suppose 5|(k^5 - k). thus k^5 - k = 5a for some a ∈ z.

   observe that

   (k + 1)^5 - (k + 1) = k^5 + 5k^4 + 10k^3 + 10k^2 + 5k + 1 - k - 1
                       = (k^5 - k) + 5k^4 + 10k^3 + 10k^2 + 5k
                       = 5a + 5k^4 + 10k^3 + 10k^2 + 5k
                       = 5(a + k^4 + 2k^3 + 2k^2 + k)

this shows that (k + 1)^5 - (k + 1) is a multiple of 5, so 5|((k + 1)^5 - (k + 1)) is true.

we have now shown that 5|(k^5 - k) implies 5|((k + 1)^5 - (k + 1)).

it follows by induction that 5|(n^5 - n) for all non-negative integers n.
#+end_quote

#+begin_note
Note that both of the probelms are solved for ∀x ∈ N, Sn. Not for ∀x ∈ Z, Sn. Since for the last one you would also have to prove statements S0, S-1. S-2, ...
#+end_note


#+begin_note
=Just a little trick=

You know that you can add equla quantities to both sides of an equation without violating equality. But don't forget that you can also add /unequal/ quantities to both sides of /inequality/! This works as long as you add smaller quantity to the smaller side and bigger quantity to the bigger side.
#+end_note

#+begin_quote
*proposition* The inequality 2^n <= 2^(n+1) - 2^(n-1) - 1 holds for each n ∈ N

proof. We will prove this with mathematical induction

1. If n = 1, this statement is:
   2^1 <= 2^(1+1) - 2^(1-1) - 1  <=> 2 <= 4 - 1 - 1
   which is obviously true.
2. Say k >= 1. We use direct proof to show that 2^k <= 2^(k+1) - 2^(k-1) - 1 implies 2^(k+1) <= 2^((k+1)+1) - 2^((k+1)-1) - 1. Suppose 2^k <= 2^(k+1) - 2^(k-1) - 1. Then

   2^k <= 2^(k+1) - 2^(k-1) - 1
   2(2^k) <= 2(2^(k+1) - 2^(k-1) - 1)  (multiply both sides by 2)
   2^(k+1) <= 2^(k+2) - 2^k - 2
   2^(k+1) <= 2^(k+2) - 2^k - 2 + 1   (add 1 to the bigger side)
   2^(k+1) <= 2^(k+1+1) - 2^k - 1
   2^(k+1) <= 2^(k+1+1) - 2^(k+1-1) - 1

It follows by induction that 2^k <= 2^(k+1) - 2^(k-1) - 1 for each n ∈ N
#+end_quote

* 10.2 Proof by Strong Induction
