#+title: Relations
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-21>
#+lastmod: <2025-10-24 11:58>
#+options: num:t
#+startup: overview

* Book of proof
** 11.1 Relations
#+begin_quote
*Definition 11.1* A relation on a set A is a subset R ∈ A x A. We often abbreviate the statement (x, y) ∈ R as xRy. The statement (x, y) ∉ R is abbreviated x!Ry.
#+end_quote

#+begin_quote
*Example 11.1* Let A = {1, 2, 3, 4}, and consider the following set:

R = {(1, 1), (2, 1), (2, 2), (3, 3), (3, 2), (3, 1), (4, 4), (4, 3), (4, 2), (4, 1)} ⊆ A x A.

The set R is a relation on A, by the definition 11.1. Since (1, 1) ∈ R, we have 1R1. Similarly, 2R1 and 2R2, and so on. However, notice that (3, 4) ∉ R, so 3!R4. Observe that R is the familiar relation >= for the set A.
#+end_quote

#+begin_quote
*Example 11.2* Let A = {1, 2, 3, 4}, and consider the following set:

R = {(1, 1), (1, 3), (3, 1), (2, 2), (3, 3), (2, 4), (4, 4), (4, 2)} ⊆ A x A.

Here we have 1S1, 1S3, 4S2, etc., but 3!S4 and 2!S1. What does this mean? Think of it as meaning "has the same parity as." Thus 1S1 reads "1 has the same parity as 1," and 42 reads "4 has the same parity as 2".
#+end_quote

#+begin_quote
*Example 11.3* Consider relation R and S of the previous two examples. Note that R∩S = {(1, 1), (2, 2), (3, 3), (3, 1), (4, 4), (4, 2)} ⊆ A x A is a relation on A.

The expression x(R∩S)y means "x >= y, and has the same parity as y."

#+end_quote

#+begin_quote
*Example 11.4* Let B = {0, 1, 2, 3, 4, 5}, and consider the following set:

U = {(1, 3), (3, 3), (5, 2), (2, 5), (4, 2)} ⊆ B x B.

The relation U is a relation on B because U ⊆ B x B. You may be hard-pressed to invent any "meaning" for this particular relation. A relation does not have to have any meaning, Any random subset of B x B is a relation on B, whether or not is describes anything familiar.
#+end_quote

** 11.2 Properties of Relations
A relational expression xRy is an open sentence; it is either true or false. For example, 5 < 10 is true, while 10 < 5 is false. Since relational expression have T/F values, we can combine them with logical operators; for example, xRy --> yRx is a statement or open sentence whose truth or falsity may depend on x and y.

#+begin_quote
*Definition 11.2* Suppose R is a relation on set A.
1. Relation R is reflexive if xRx for every x ∈ A.
   That is, R is reflexive if ∀x ∈ A, xRx.

2. Relation R is symmetric if xRy implies yRx for all x,y ∈ A.
   That is R is symetric if ∀x,y ∈ A, xRy --> yRx.

3. Relation is transitive if whenever xRy and yRz, them also xRz.
   That is R is transitive if ∀x,y,z ∈ A, ((xRy)∧(yRz)) --> yRx.
#+end_quote

|------------------+-----+------+-----+-----+------+------|
| *Relations on Z* | *<* | *<=* | *=* | *I* | *!I* | *!=* |
|------------------+-----+------+-----+-----+------+------|
| *Reflexive*      | no  | yes  | yes | yes | no   | no   |
| *Symmetric*      | no  | no   | yes | no  | no   | yes  |
| *Transitive*     | yes | yes  | yes | yes | no   | no   |
|------------------+-----+------+-----+-----+------+------|
#+begin_quote
*Example 11.7* A = {b, c, d, e}, and R is the following relation on A:
R = {(b,b), (b,c), (c,b), (c,c), (d,d), (b,d), (d,b), (c,d), (d,c)}.

This relation is *not reflexive*, for although bRb, cRc, and dRd, it is not true taht eRe. For relation to be reflexive, xRx must be true for all x ∈ A.


The relation R *is symmetric*, because whenever we have xRy, it follows that yRx too.

(b,c) and (c,b); (b,d) and (d,b); (c,d) and (d,c).

However, if we take out any of them, R would stop being symmetric.


The relation R *is also transitive*, but it takes some work to check it.

We must check that the statement (xRy ∧ yRz) --> xRz is true for all x,y,z ∈ A.

For example, taking x = b, y = c, z = d, we have (bRd ∧ dRc) --> bRc is true.
#+end_quote

** 11.3 Equivalence Relations
#+begin_quote
*Definition 11.3* A relation R on set A is an *equivalence relation* if it is reflexive, symmetric and transitive.
#+end_quote

* proofs james cummings
** 9.1 Equivalence Relations
Consider modular arithmetics:

        -2 ≡ 3 (mod 5)
         3 ≡ 3 (mod 5)
         8 ≡ 3 (mod 5)
        13 ≡ 3 (mod 5)

Since, -2, 3, 8, 13 are all equivalen tto 3 (mod 5), there is an equivalence of sorts between these numbers. This can be seen if we flip the order and get:

        3 ≡ -2 (mod 5)
        3 ≡  3 (mod 5)
        3 ≡  8 (mod 5)
        3 ≡ 13 (mod 5)

Furthermore, -2 ≡ 3 (mod 5) and 3 ≡ 13 (mod 5), show that both -2 and 13 are congruent to 3 (modulo 5), but more than that, they are also congruent to each other as -2 ≡ 13 (mod 5)

So in this mod-5 way, every number in {-2, 3, 8, 13} is equivalent to every other number in this set, inlcuding to itself. And this will extend:

        *Mod-5 Property.* If you pick any two numbers in the set

        - {..., -10, -5, 0, 5, 10, 15, 20, 25, ...},

        then they will be mod-5 equivalent to each other. Moreover, each number in this set is also mod-5 equivalent to itself. This property also holds for each of the following sets:

        - {..., -9, -4, 1, 6, 11, 16, ...}
        - {..., -8, -3, 2, 7, 12, 17, ...}
        - {..., -7, -2, 3, 8, 13, 18, ...}
        - {..., -6, -1, 4, 9, 14, 19, ...}

        These five sets are called the /equivalence classes/ of the mod-5 /equivalence relation/. They also have this important property: They completely particion Z; that is, every integer is in precisely one of these sets.

/Little recap/ A partition is simply any way to break up a set into a collection of subsets.

#+begin_quote
*Definition 9.1.* A partition of a set A is a collection of non-empty subsets of A for which each element of A is in one and only one of the subsets.
#+end_quote

/New symbol:/ ~
        a ~ b     if     a ≡ b (mod 5).
        (so ~ just shows the relation between the a and b)

#+begin_quote
- a ~ a for all a ∈ Z;
- If a ~ b, then b ~ a for all a, b ∈ Z;
- If a ~ b and b ~ c, then a ~ c for all a, b, c ∈ Z.
#+end_quote

If the following bullet points are all followed by the partition, then the relation is equivalent.

#+begin_quote
*Definition 9.3.* An /equivalence relation/ on set A is an ordered relationship between pairs of elements of A for which the pair is either related or is not related. If a, b ∈ A, we denote a ~ b if a is related to b, and a !~ b if a is not related to b.

For ~ to be an equivalence realtion, it also must satisfy the following three properties:

- Reflexive: a ~ a for all a ∈ A;
- Symmetric: If a ~ b, then b ~ a for all a,b ∈ A;
- Transitive: If a ~ b and b ~ c, then a ~ c for all a,b,c ∈ A.

Lastly, if ~ is an equivalence relation and a ∈ A, define the equivalence class containint a to be the set
        {b ∈ A: a ~ b}
#+end_quote

#+begin_quote
*Definition 9.4.* A /relation/ on a set A is any ordered relationship between pairs of elements of A

#+end_quote
