#+title: Lesson 2
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-02>
#+lastmod: <2025-10-04 14:48>
#+options: num:t
#+startup: overview

* Lecture Notes: Sets and Elements

- Sets :: A set is a collection of distinct objects, referred to as elements.

   - Example: S = {1, 2, 3}, A = {apple, 2, student}, B = {2, 3, 1}. Two sets are equal if they contain the same elements, irrespective of the order. So, B = S.

   - A set's uniqueness means that the set C = {1, 2, 3, 3, 1} is identical to S, despite repeated elements.

   - Notation: If =x= is an element of =A=, we model this as =x ∈ A=. If =x= is not an element of =A=, we say =x ∉ A=.

- Empty set :: This is a set with no elements.

- Cardinality :: The cardinality of a finite set is the number of distinct elements in that set.

- Number sets:

   - N = Natural numbers = {1, 2, 3, ...}
   - Z = Integers = {... -2, -1, 0, 1, 2, ...}
   - R = Real numbers.

- Set-builder notation: =S = {expression : rules}=.

   - Example: A = {a ∈ N : a < 5}, resulting in A = {1, 2, 3, 4}.

- Rational numbers' set: Q = {m/n : m ∈ Z, n ∈ N}, where =m= and =n= are integers and natural numbers respectively.

- Cartesian Product:

   - An ordered pair (a, b) is not equal to (b, a) unless a = b.
   - For sets =A= and =B=, the Cartesian product of =A= and =B= is defined as A x B = {(a, b) : a ∈ A, b ∈ B}.

   - Example: If A = {1, 2} and B = {a, b}, then A x B = {(1, a), (1, b), (2, a), (2, b)}.

- Subset :: A is called a subset of B if every element of A is also an element of B.

The first theorem:
If the set S has n elements, then it has 2^n subsets

The power set of the set A is the set that contains all subsets of A

Notation is 2^A

** Basic operations
- The Union of A and B is the set of elements that are either A or B
  A ∪ B = {x : x ∈ A or x ∈ B}

- The intersection of A and B is the set of elements that are both in A and B
  A ∩ B = {x : x ∈ A or x ∈ B}

- The difference between A and B is the set of elements that are in A but not in B
  A \ B


U is the


U is the universal set

the complement of the set A is the U \ A
Notation: A^c = U \ A
