#+title: Ps 10
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-05-23>
#+lastmod: <2026-05-26 12:04>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages

* Problem 1 :newton_method:nonlinear_system:jacobian:
** Task
#+begin_quote
Given $f : \mathbb{R}^2 \to \mathbb{R}^2$ by

$$f(x, y) = \begin{pmatrix} x^2 + y^2 - 1 \\ x - y \end{pmatrix}$$

(a) Determine all $(x, y)^\top \in \mathbb{R}^2$ such that $f(x, y) = 0$.

(b) By using the initial vector $X_0 = (1, \frac{1}{2})^\top \in \mathbb{R}^2$, apply the Newton iteration twice by hand to compute $X_2$. How big is the error?
#+end_quote

** Solution
*** (a)

Setting $f(x, y) = 0$ gives $x^2 + y^2 = 1$ and $x = y$. Substituting:

$$2x^2 = 1 \implies x = \pm\frac{1}{\sqrt{2}}$$

So the solutions are $\left(\frac{1}{\sqrt{2}}, \frac{1}{\sqrt{2}}\right)^\top$ and $\left(-\frac{1}{\sqrt{2}}, -\frac{1}{\sqrt{2}}\right)^\top$.

*** (b)

$$J_f(x, y) = \begin{pmatrix} 2x & 2y \\ 1 & -1 \end{pmatrix}$$

**Iteration 1:**

\begin{align*}
X_0 &= \begin{pmatrix} 1 \\ 1/2 \end{pmatrix} \\
f(X_0) &= \begin{pmatrix} 1/4 \\ 1/2 \end{pmatrix} \\
J_f(X_0) &= \begin{pmatrix} 2 & 1 \\ 1 & -1 \end{pmatrix} \\
[J_f(X_0)]^{-1} &= -\frac{1}{3} \begin{pmatrix} -1 & -1 \\ -1 & 2 \end{pmatrix} \\
X_1 &= X_0 - [J_f(X_0)]^{-1} f(X_0) \\
&= \begin{pmatrix} 1 \\ 1/2 \end{pmatrix} - \left[ -\frac{1}{3} \begin{pmatrix} -1 & -1 \\ -1 & 2 \end{pmatrix} \right] \begin{pmatrix} 1/4 \\ 1/2 \end{pmatrix} \\
&= \begin{pmatrix} 3/4 \\ 3/4 \end{pmatrix}
\end{align*}

**Iteration 2:**

\begin{align*}
f(X_1) &= \begin{pmatrix} 1/8 \\ 0 \end{pmatrix} \\
J_f(X_1) &= \begin{pmatrix} 3/2 & 3/2 \\ 1 & -1 \end{pmatrix} \\
[J_f(X_1)]^{-1} &= -\frac{1}{3} \begin{pmatrix} -1 & -3/2 \\ -1 & 3/2 \end{pmatrix} = \begin{pmatrix} 1/3 & 1/2 \\ 1/3 & -1/2 \end{pmatrix} \\
X_2 &= X_1 - [J_f(X_1)]^{-1} f(X_1) \\
&= \begin{pmatrix} 3/4 \\ 3/4 \end{pmatrix} - \begin{pmatrix} 1/3 & 1/2 \\ 1/3 & -1/2 \end{pmatrix} \begin{pmatrix} 1/8 \\ 0 \end{pmatrix} \\
&= \begin{pmatrix} 17/24 \\ 17/24 \end{pmatrix}
\end{align*}

**Error:**

\begin{align*}
\|X_2 - X^*_1\|_\infty &= \left| \frac{17}{24} - \frac{1}{\sqrt{2}} \right| \approx 0.00122 \\
\|X_2 - X^*_1\|_2 &= \frac{17\sqrt{2}}{24} - 1 \approx 0.00173
\end{align*}

* Problem 2 :newton_method:numerical_methods:linear_system:
** Task
#+begin_quote
Implement Newton's method numerically (use Julia's Linear Algebra package to solve a system of linear equations $Ax = b$ needed in each iteration by $A \backslash b$). Test your code for a few meaningful examples, in particular, solve the exercises above using your implementation.
#+end_quote

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_2.jl
#+end_src

* Problem 3 :newton_method:nonlinear_system:jacobian:
** Task
#+begin_quote
Consider $f : \mathbb{R}^2 \to \mathbb{R}^2$ given by
$$f(x, y) = \begin{pmatrix} x^2 - y \\ y^2 - x \end{pmatrix}$$

(a) Find all solutions of $f(x, y) = 0$.

(b) Determine all points where the Jacobian of $f$ is not invertible and visualize those points in Julia.

(c) Investigate in Julia what happens when Newton's method is initialized near a point for which the Jacobian is not invertible.
#+end_quote

** Solution
*** (a)

*** (b)
#+begin_src julia :results value :exports both :tangle julia/p_3b.jl
#+end_src

*** (c)
#+begin_src julia :results value :exports both :tangle julia/p_3c.jl
#+end_src

* Problem 4 :newton_method:convergence:gradient:
** Task
#+begin_quote
Answer the following questions:

1. What does the Newton iterations do for the linear system of equations $Ax - b = 0$, where $A \in \mathbb{R}^{n\times n}$ and $b \in \mathbb{R}^n$?

2. Find a sequence $(x_k)_{k\in\mathbb{N}} \subset \mathbb{R}^n$ that converges linearly towards some $x^* \in \mathbb{R}^n$ but not quadratically.

3. Find a sequence $(x_k)_{k\in\mathbb{N}} \subset \mathbb{R}^n$ that converges quadratically towards some $x^* \in \mathbb{R}^n$.

4. Visualize the two aforementioned sequence in Julia by using suitable plots with logarithmic axis labels.

5. Compute the gradient of $f(x) = \|Ax - b\|^2$ for $A \in \mathbb{R}^{n\times n}$ and $b \in \mathbb{R}^n$. Apply the Newton method to the gradient of $f$. What do you observe?
#+end_quote

** Solution
*** 1.

*** 2.

*** 3.

*** 4.
#+begin_src julia :results value :exports both :tangle julia/p_4_4.jl
#+end_src

*** 5.

* Time Estimates
- Problem 1: ~30 min~
- Problem 2: ~45 min~
- Problem 3: ~40 min~
- Problem 4: ~50 min~
