#+title: How To Study
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-24>
#+lastmod: <2025-10-25 11:50>
#+options: num:t
#+startup: overview

* Core techniques to adopt
1. *Active recall every session.* Read definition/theorem for 30-60 seconds and then try to reproduce it from memory. Do until you can write it perfectly.

2. *Spaced Repitition System (SRS).* Use Anki/org-drill to force repeated retrival at expanding intervals. Extract crucial part.

3. *Problem first learning.* Start a session by attempting to solve the problem set. Write out all thoughts and ideas and evaluate them after reading the book.

4. *Deliberate error logging.* Keep all the "first attempts". For each mistake write a statement, my wrong approach, explanation why it failed, correct fix, and 1-sentence principle to remember.

5. *Worked example.* Study the worked proof, then redo the proof with some steps removed, and in the end produce the whole proof by myself.

6. *Chunking / Mental models.* Reduce complex proofs to a smaller number of "moves" or lemmas I can apply like a tool.

* Small tricks
- Link the notes to the book page it is referencing. (org-noter)
- Write the Julia problems in org-babel.
  - [[https://www.youtube.com/watch?v=D3FzMPZm7vY&t=644s][Video]] on exporting a src blocks from org to src files

* TODO
- [ ] Research on the anki extension in emacs and org-drill.
- [ ] Start logging the errors in the problem sets inside of the folded star in the end.
- [ ] Have a look on the org-agenda and org-habit.
- [ ] Also have a look on the pomodoro technique. If it is worth it, then use org-pomodoro.
- [ ] Check C-c C-d

* Personal study method
1. Go though the problem set. Try to solve the questions by yourself. Keep all notes/solutions.

   This will help to fully analyse the problems thoroughly, seeing personal thinking pattern.

2. Go through problems, noting what sub-topic does each problem relate to. If do not know, use help of LLM, but only request the topics of the problems!

   This would help to focus on the relevant chapters of the books.

3. Go through the book chapters outlined by the problems.

   Saw definition/theorem?
   - Read for 60 seconds and then reproduce it from memory.
   - Write it down into org-drill cards.

   Saw proof?
   - Redo the proof with some steps removed. Repeat until reproduce whole proof.
   - Break down the proof to smaller steps or lemmas. Systemize it.

4. Go back to problem set and try to solve it alone.

5. If some questions are too hard, search on the internet. LLM last option (provide error logs for analysis).

- Why this method?
  As professors have said, exams are going to be based on the problem sets fully. This means that if problem sets are used wisely, they will help to reduce the amount of potentially "unrelevant" information to learn, by simply following the books.

  Also the course topics are being taught randomly, with no strict sequence of book chapters. Some of the topics are not even in the books. This removes the accent from the book style education (more systematic) to a more flexible style, shifting the educational base fully on problem sets.
