#+title: How To Study
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-24>
#+lastmod: <2025-10-24 21:39>
#+options: num:t
#+startup: overview

* Core techniques to adopt
1. *Active recall every session.* Read definition/theorem for 30-60 seconds and then try to reproduce it from memory. Do until you can write it perfectly.

2. *Spaced Repitition System (SRS).* Use Anki/org-drill to force repeated retrival at expanding intervals. Extract crucial part.

3. *Problem first learning.* Start a session by attempting to solve the problem set. Write out all thoughts and ideas and evaluate them after reading the book.

4. *Deliberate error logging.* Keep all the "first attempts". For each mistake write a statement, my wrong approach, explanation why it failed, correct fix, and 1-sentence principle to remember.

5. *Worked example.* Study the worked proof, then redo the proof with some steps removed, and in the end produce the whole proof by myself.

6. *Chunking / Mental models.* Reduce complex proofs to a smaller number of "moves" or lemmas I can apply like a tool.

* Small tricks
- Link the notes to the book page it is referencing. (org-noter)
- Write the Julia problems in org-babel.
- Have a look on

* TODO
- [ ] Research on the anki extension in emacs and org-drill.
- [ ] Start logging the errors in the problem sets inside of the folded star in the end.
- [ ] Have a look on the org-agenda and org-habit.
- [ ] Also have a look on the pomodoro technique. If it is worth it, then use org-pomodoro.
- [ ] Check C-c C-d
