#+title: Day 6 — Sat Jul 04 · Mock-1 repair + time-drills + MC
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-07-02>
#+lastmod: <2026-07-06 13:40>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages
#+columns: %50ITEM(Item) %8LECTURE_REF(Lecture) %34CUSTOM_ID(ID)

* DONE PS13 P03
** Task
#+begin_quote
Consider $f : \mathbb{R}^2 \to \mathbb{R}$ given by

$$f(x) = x_1^2 + 2x_2^2$$

subject to the constraint

$$g(x) = x_1^2 + x_2^2 - 1 = 0$$.

Use the Lagrangian and its Hessian to identify the local minimum of the restriction of $f$. Visualize your result in Julia.
#+end_quote

** Solution

Since $\nabla g(x) \neq 0$ on $M = \{g(x) = 0\}$, Lagrange multipliers corrollary gives that every constraint extremum satisfies $\nabla f(x) = \lambda \nabla g(x)$ for some $\lambda \in \mathbb{R}$.

\begin{align*}
\nabla f(x) &=
\begin{pmatrix}
2x_1 \\
4x_2
\end{pmatrix} \\
\nabla g(x) &=
\begin{pmatrix}
2x_1 \\
2x_2
\end{pmatrix} \\
\begin{pmatrix}
2x_1 \\
4x_2
\end{pmatrix} &=
\lambda
\begin{pmatrix}
2x_1 \\
2x_2
\end{pmatrix} \\
&\Rightarrow
\begin{cases}
2x_1 = \lambda 2x_1 \quad \Rightarrow (\lambda = 1) \\
4x_2 = \lambda 2x_2 \quad \Rightarrow (\lambda = 2) \\
x_1^2 + x_2^2 - 1 = 0
\end{cases} \\
\end{align*}

\begin{align*}
\lambda &= 1 \Rightarrow x_2 = 0 \Rightarrow x_1 = \pm 1 \\
\lambda &= 2 \Rightarrow x_1 = 0 \Rightarrow x_2 = \pm 1 \\
\end{align*}

Thus, $(\pm 1, 0),\ (0, \pm 1)$.

\begin{align*}
H_f(x) &=
\begin{pmatrix}
2 & 0 \\
0 & 4
\end{pmatrix} \\
H_g(x) &=
\begin{pmatrix}
2 & 0 \\
0 & 2
\end{pmatrix} \\
H_L(x) &=
\begin{pmatrix}
2 - 2 \lambda & 0 \\
0 & 4 - 2 \lambda
\end{pmatrix} \\
\end{align*}

- $(\pm 1, 0),\ \lambda = 1$:

  \begin{align*}
  T_p &= \ker(g'(x)) = \mathrm{span}(0,1) \\
  v &= (0,1)^{\top} \\
  v (H_L)v^{\top} &=
  \begin{pmatrix}
  0 & t
  \end{pmatrix}
  \begin{pmatrix}
  0  & 0 \\
  0 & 2
  \end{pmatrix}
  \begin{pmatrix}
  0 \\ t
  \end{pmatrix} \\
  &= 2t^2 > 0 \Rightarrow \text{min}
  \end{align*}

- $(0, \pm 1),\ \lambda = 2$:

  \begin{align*}
  T_p &= \ker(g'(x)) = \mathrm{span}(1,0) \\
  v &= (0,1)^{\top} \\
  v (H_L)v^{\top} &=
  \begin{pmatrix}
  t & 0
  \end{pmatrix}
  \begin{pmatrix}
  -2 & 0 \\
  0 & 0
  \end{pmatrix}
  \begin{pmatrix}
  t \\ 0
  \end{pmatrix} \\
  &= -2t^2 < 0 \Rightarrow \text{max}
  \end{align*}

* PS07 P01
** Task
#+begin_quote
Let $f : (-\frac{1}{2}, \infty) \times (-\frac{1}{2}, \infty) \to \mathbb{R}$ be defined by

\[ f(x, y) = \log(1 + x + y) \]

(a) Determine the Taylor polynomial of order 3 of $f$ at $(0, 0)$.
(b) Use your result to approximate $f(0.1, 0.1)$.
(c) Plot heatmaps of $f$, of the Taylor polynomial of order 3, and of the difference of the two in $[0, 1]^2$.
#+end_quote

** Solution

*** (a)

$T_3(x) = f(x_0) + (\nabla f(x_0))^{\top}(x - x_0) + \frac{1}{2}(x - x_0)^{\top}H_f(x_0)(x - x_0)$

*** (b)
*** (c)
* DONE PS02 P04
** Task
#+begin_quote
Let $f : [0, 1] \to \mathbb{R}$ be given by

$$f(x) = \frac{1}{4}(x^2 + 1)$$

(a) Show that $f$ maps $[0, 1]$ into itself and is a contraction on $[0, 1]$.

(b) Deduce that $f$ has a unique fixed point and implement the fixed point iteration in Julia.
#+end_quote

** Solution

*** (a)

\begin{align*}
x \in [0,1] &\implies x^2 \subseteq [0,1] \\
            &\implies x^2 + 1 \subseteq [1,2] \\
            &\implies \frac{1}{4}(x^2 + 1) \subseteq \left[\frac{1}{4},\frac{1}{2}\right] \\
\end{align*}

As $\left[\frac{1}{4},\frac{1}{2}\right] \in [0,1]$, $f$ maps $[0,1]$ to itself.

\begin{align*}
|f(x) - f(y)| &= \frac{1}{4}|x^2 + 1 - y^2 - 1| \\
              &= \frac{1}{4}|x^2 - y^2| \\
              &= \frac{1}{4}|x - y||x + y| \\
              &\le \frac{1}{4}2|x - y| \\
              &= \frac{1}{2}|x - y| \\
\end{align*}

Thus, $f$ is a contraction on $[0,1]$ with $L = \frac{1}{2}$.

*** (b)

Given completeness of $([0,1], d_1)$ and a contraction function $f$, by Banach fixed point theorem, there exists unique fixed point $x \in [0,1] : f(x) = x$.

* DONE PS11 P04 cstm
** Task
#+begin_quote
Let

$$M = \{(x, y, z)^\top \in \mathbb{R}^3 : g_1(x, y, z) = 0,\ g_2(x, y, z) = 0\},$$

where

\begin{align*}
g_1(x, y, z) &= x^2 + y^2 - 2z, \\
g_2(x, y, z) &= x + y + z - 4.
\end{align*}

Show that $M$ is a 1-dimensional submanifold of $\mathbb{R}^3$.
#+end_quote

** Solution

Define:


\begin{align*}
g(x,y,z) &= \begin{pmatrix} g_1(x,y,z) \\ g_2(x,y,z) \end{pmatrix} \\
         &= \begin{pmatrix} x^2 + y^2 - 2z \\ x + y + z - 4 \end{pmatrix} \\
\end{align*}

Choose $g : \mathbb{R}^3 \rightarrow \mathbb{R}^2$, $M = \{g(x,y,z) = 0\}$. $g \in \mathcal{C}^1$, as $g_1, g_2$ are polynomials. Then $k = 2$, $r = n - k = 1$.

Choose $U = \mathbb{R}^3$. $M \cap U = \{g(x,y,z) = 0\} = M$.

\begin{align*}
\nabla g(x,y,z) &=
\begin{pmatrix}
2x & 2y & -2 \\
1 & 1 & 1
\end{pmatrix}
\end{align*}

Rows are linearly dependent iff $(2x, 2y, -2) = \lambda (1, 1, 1)$ for some $\lambda$, forcing $x,y = -1$.

Validate $x,y = -1$:

\begin{align*}
(-1)^2 + (-1)^2 - 2z &= 0 \implies z = 1 \quad (g_1) \\
(-1) + (-1) + 1 &\neq 0 \quad (g_2) \\
\end{align*}

Thus, $x,y = -1$ are not in $M$.

$\nabla g(x,y,z) \neq 0\ \forall x,y,z \in \mathbb{R}$, and $\mathrm{rank}(\nabla g) = 2$.

Thus, by definition of submanifold, $M$ is 1 dimensional submanifold of $\mathbb{R}^3$.
